#!/usr/bin/env python3
"""
pcsoft-schema-to-sql.py - Generate DDL + an ER diagram from a converted PCSoft HFSQL analysis.

Input : pre-convert/*.table.md  (one per data file) and pre-convert/_schema.md (Links section).
Output: rebuild/db/schema.<dialect>.sql  - faithful DDL (names/types kept 1:1)
        rebuild/db/ER-diagram.md          - Mermaid erDiagram + per-table field docs + migration notes

Field names and types are kept verbatim (the "Keep as-is / faithful" choice). The HFSQL type is
mapped to the nearest target type without renaming or restructuring anything.

Usage:
    python scripts/pcsoft-schema-to-sql.py --dialect firebird --out rebuild/db
"""
import argparse
import json
import hashlib
import unicodedata
import sys
import glob
import os
import re

import os as _wmos, sys as _wmsys
_wmsys.path.insert(0, _wmos.path.dirname(_wmos.path.abspath(__file__)))
import wxconv_redact as rd  # noqa: E402 - the watermark stamp now lives inside rd.write_text()

# HFSQL type -> target type, per dialect. (col_type, is_identity_pk)
TYPEMAP = {
    "firebird": {
        "uint2": "INTEGER", "float4": "FLOAT",
        "identifier": "BIGINT",            # + GENERATED BY DEFAULT AS IDENTITY (Firebird 3+)
        "int8": "BIGINT", "int4": "INTEGER", "uint4": "BIGINT", "uint1": "INTEGER",
        "varchar": "VARCHAR({n})", "uvarchar": "VARCHAR({n})",
        "text": "BLOB SUB_TYPE TEXT", "blob": "BLOB SUB_TYPE BINARY",
        "boolean": "BOOLEAN", "date": "DATE", "time": "TIME", "datetime": "TIMESTAMP",
        "numeric": "NUMERIC(18,4)", "double": "DOUBLE PRECISION",
    },
    "postgres": {
        "uint2": "INTEGER", "float4": "REAL",
        "identifier": "BIGINT", "int8": "BIGINT", "int4": "INTEGER", "uint4": "BIGINT",
        "uint1": "INTEGER", "varchar": "VARCHAR({n})", "uvarchar": "VARCHAR({n})",
        "text": "TEXT", "blob": "BYTEA", "boolean": "BOOLEAN", "date": "DATE",
        "time": "TIME", "datetime": "TIMESTAMPTZ", "numeric": "NUMERIC(18,4)",
        "double": "DOUBLE PRECISION",
    },
    "mssql": {
        "uint2": "INT", "float4": "REAL",
        "identifier": "BIGINT", "int8": "BIGINT", "int4": "INT", "uint4": "BIGINT",
        "uint1": "INT", "varchar": "NVARCHAR({n})", "uvarchar": "NVARCHAR({n})",
        "text": "NVARCHAR(MAX)", "blob": "VARBINARY(MAX)", "boolean": "TINYINT", "date": "DATE",
        "time": "TIME", "datetime": "DATETIME2", "numeric": "DECIMAL(18,4)",
        "double": "FLOAT",
    },
    "mysql": {
        "uint2": "INT UNSIGNED", "float4": "FLOAT",
        "identifier": "BIGINT", "int8": "BIGINT", "int4": "INT", "uint4": "INT UNSIGNED",
        "uint1": "INT", "varchar": "VARCHAR({n})", "uvarchar": "VARCHAR({n})",
        "text": "LONGTEXT", "blob": "LONGBLOB", "boolean": "TINYINT(1)", "date": "DATE",
        "time": "TIME", "datetime": "DATETIME", "numeric": "DECIMAL(18,4)", "double": "DOUBLE",
    },
}

# HFSQL type label (as it appears in the doc) -> internal key. Order matters (longest first).
HFSQL = [
    ("Automatic identifier", "identifier"),
    ("Unsigned 4-byte integer", "uint4"),
    ("Unsigned 2-byte integer", "uint2"),
    ("Unsigned 1-byte integer", "uint1"),
    ("8-byte integer", "int8"),
    ("4-byte integer", "int4"),
    ("4-byte real", "float4"),
    ("8-byte real", "double"),
    ("Unicode Text Memo", "text"),
    ("Unicode string", "uvarchar"),
    ("Binary string", "blob"),    # field-reported; developer-confirmed via --type-map
    ("Other binary memo", "blob"),
    ("Image (binary memo)", "blob"),
    ("Binary memo", "blob"),
    ("Text Memo", "text"),
    ("Memo", "text"),
    ("Composite key", "composite"),
    ("Boolean", "boolean"),
    ("Date and Time", "datetime"),
    ("DateTime", "datetime"),
    ("Date", "date"),
    ("Time", "time"),
    ("Currency", "numeric"),
    ("Monetary", "numeric"),
    ("Numeric", "numeric"),
    ("Decimal", "numeric"),      # field-reported; confirmed by the developer via --type-map
    ("Real", "double"),
    ("Double", "double"),
    ("String", "varchar"),
]
TYPE_STARTS = [lbl for lbl, _ in HFSQL]

# The field-dictionary table's OWN column headers. Every one of these must be listed: the strip
# below walks the header block until it meets a line that is not a header, so a single missing
# label ends the strip early and the rest of the block is read as field data — the first surviving
# label becomes the first field's NAME and every field after it shifts by one position.
# "GDPR" is a fixed column in this document family (the analysis records per-item GDPR flagging);
# it was absent here, which is exactly how that one-position cascade was reaching real conversions.
HEADER_LABELS = {"Caption", "Type", "Size", "Unique Key", "Key with Duplicates",
                 "Direction", "GDPR", "Default value"}

# A line whose whole content is a date/time FORMAT annotation, e.g. "(yyyymmddhhmmssccc)".
# PCSoft prints it as a continuation line immediately under the type label of a Date / Time /
# Date and Time item. It belongs to the type, not to the next field, so it must be consumed with
# the type — left in place it is read as the NEXT field's name and shifts everything after it.
DATE_FORMAT_ANNOTATION_RE = re.compile(r"^\([ymdhsc]+\)$")

# A bare single capitalized word in the TYPE position, immediately followed by a purely numeric
# line, is the "Type / Size" shape this document family uses for every sized type (String width,
# Composite key member count, and so on). When that word is not a type we know, it is an unmapped
# type — the same defect class SUSPECT_TYPE_RE catches for the "<n>-byte <word>" family, which a
# one-word type such as "Decimal" slips straight past.
BARE_TYPE_RE = re.compile(r"^[A-Z][A-Za-z]*$")
NUMERIC_LINE_RE = re.compile(r"^\d+$")

# An HFSQL item name is an identifier: no spaces, no punctuation, accents allowed (Complément).
# Some items carry a free-text NOTE under their default value — an enumeration legend such as
#     FR:
#     1 : Monsieur
#     2 : Madame
# Those lines are neither a field nor a stray the scan can skip: one of them starts a "record"
# whose type search reaches down into the NEXT field's type line, so the note line becomes a
# column and the real field below it is consumed as part of its caption. Requiring the name to
# look like an identifier costs nothing real — an item name cannot contain a space — and it puts
# the scan back on the next genuine item.
ITEM_NAME_RE = re.compile(r"^[A-Za-z_À-ɏ][A-Za-z0-9_À-ɏ]*$")


# "<n>-byte integer" / "<n>-byte real" is a WIDTH, not a distinct type, so it does not need a table
# entry or a human to interpret it — PCSoft emits widths this kit has never seen (2, 6, ...) and the
# right answer is always "the smallest target integer that holds n bytes". Deriving it means an
# unseen width converts correctly instead of stopping the run; only a genuinely unknown WORD
# ("6-byte duration") still needs asking about.
BYTE_TYPE_RE = re.compile(r"^(unsigned\s+)?(\d+)-byte\s+(integer|int|real|float)\b", re.I)

# Integers land on exactly TWO target types: INTEGER and BIGINT. In practice HFSQL emits 4- and
# 8-byte integers, and anything narrower (1-, 2-byte) is widened to INTEGER rather than given its
# own SMALLINT/TINYINT. Widening is always safe and keeps the converted schema from sprouting
# narrow types the application never needed; narrowing never is, so nothing rounds down.
_SIGNED_WIDTHS = ((4, "int4"), (8, "int8"))
_UNSIGNED_WIDTHS = ((2, "int4"), (4, "uint4"))   # unsigned 4-byte needs BIGINT to hold its range
_WIDEST_INT = "int8"                              # anything above 8 bytes still lands on BIGINT


def derive_byte_type(label):
    """Map an '<n>-byte integer/real' label to a key by width. None if not that shape."""
    m = BYTE_TYPE_RE.match(label)
    if not m:
        return None
    unsigned, nbytes, family = bool(m.group(1)), int(m.group(2)), m.group(3).lower()

    if family in ("real", "float"):
        # 4 bytes is single precision; anything wider gets double. Never narrow a float.
        return "float4" if nbytes <= 4 else "double"

    widths = _UNSIGNED_WIDTHS if unsigned else _SIGNED_WIDTHS
    for width, key in widths:
        if nbytes <= width:
            return key
    return _WIDEST_INT


# WinDev's optimizer adds its own composite keys, and their CAPTION reads "Composite key added by
# the optimizer" — which starts with a real type label. Matched as a type it consumes the caption
# line, and the actual "Composite key:" line below is then swallowed into the member-column list.
# The caption is worth keeping intact anyway: it is what distinguishes an optimizer index from a
# business key when the developer reviews which ones to carry over.
_CAPTION_NOT_TYPE_RE = re.compile(r"^Composite key\s+added\b", re.I)


# A type line carries the label and NOTHING ELSE — optionally a parenthesised tail
# ("Automatic identifier (4 ", "Date (yyyymmdd)") or a colon ("Composite key: "). Plain startswith
# made every line merely BEGINNING with a type word into a type, and that is the single widest
# source of corruption in this parser, in two directions:
#   - identifiers: StringValue, RealValue, DateNewsCreation, CurrencyCode, DateOfLanding
#   - captions:    "Date time", "String value", "Real value", "Integer value"
# It matters far beyond a mislabelled column, because the parser asks "is this line a type?" to
# decide where one field ends and the next begins. On a real export, an item named StringValue
# made the parser reject the PREVIOUS field's default, which then became the next field's name and
# shifted the remainder of the table; SITE_CONFIGURATION lost three of its six columns that way.
_TYPE_TAIL_RE = re.compile(r"^\s*$|^\s*[(:]")


def _label_ends_cleanly(line, lbl):
    return bool(_TYPE_TAIL_RE.match(line[len(lbl):]))


def match_type(line):
    if _CAPTION_NOT_TYPE_RE.match(line or ""):
        return None, None
    for lbl, key in HFSQL:
        if line.startswith(lbl) and _label_ends_cleanly(line, lbl):
            return lbl, key
    derived = derive_byte_type(line)
    if derived:
        # Report the label as written in the doc, so the DDL comment stays faithful to the source.
        return line.split("(")[0].strip(), derived
    return None, None


# A line sitting in the TYPE position that we could not map. Deliberately narrow: the "<n>-byte
# <word>" family is what the field reports hit ("2-byte integer", "4-byte real") and no field
# caption realistically reads that way, so this can hard-stop a run without false positives.
# An unmapped type is not a cosmetic gap — the field is dropped from the DDL entirely, so the
# column silently disappears from the converted schema.
SUSPECT_TYPE_RE = re.compile(r"^(unsigned\s+)?\d+-byte\s+[a-z]+", re.I)


def looks_like_type_label(line):
    """Could this line plausibly be an HFSQL type label we simply do not know?

    Kept permissive on shape but strict on obvious non-labels: the cost of a false positive is one
    question to the developer, while the cost of a false negative is a column deleted from the
    schema without a word.
    """
    if not line or len(line) > 48:
        return False
    if line in HEADER_LABELS:
        return False
    if re.fullmatch(r"[-*_=.,:;/\\|#<>()\[\]{}\s]+", line):
        return False       # rules, punctuation runs, separator noise
    if re.fullmatch(r"-?[\d.,]+", line):
        return False       # a size or a default value, not a type
    return bool(re.match(r"^[A-Za-z]", line))


def register_type_overrides(pairs):
    """
    Apply --type-map "<HFSQL label>=<key>" overrides supplied by the operator.

    This is how a conversion gets unblocked the moment the developer says what an unknown type
    means, instead of waiting for a kit release. The same answer is then reported for upstream
    inclusion so the next person never sees it (see report_unmapped).
    """
    valid = set()
    for dial in TYPEMAP.values():
        valid.update(dial)
    for raw in pairs or []:
        if "=" not in raw:
            sys.exit(f"--type-map expects '<HFSQL label>=<key>', got: {raw}")
        label, key = (p.strip() for p in raw.split("=", 1))
        if not label or not key:
            sys.exit(f"--type-map expects '<HFSQL label>=<key>', got: {raw}")
        if key not in valid:
            sys.exit(
                f"--type-map: unknown key '{key}'.\n"
                f"  Valid keys: {', '.join(sorted(valid))}\n"
                f"  Pick the closest existing key; if none fits, report the type to wxKanban."
            )
        HFSQL.append((label, key))
    # match_type walks in order and uses startswith, so longest labels must be tried first or
    # "4-byte integer" would be shadowed by a shorter prefix.
    HFSQL.sort(key=lambda pair: len(pair[0]), reverse=True)


def drop_watermark_trailer(body):
    """Cut our OWN generated watermark block off the end of the field stream.

    Every .table.md ends with a separator, an HTML comment and a '*Converted with wxKanban...'
    line. They are not source content, but they sit in the field stream and land in the type
    position for the last field — so the unmapped-type gate, which reports whatever it finds
    there, would raise one false alarm per table (206 across the corpora tested) and drown the
    handful of real unmapped types in noise.
    """
    for idx, line in enumerate(body):
        if line.startswith("<!-- wxkanban:watermark")  \
                or line.startswith("*Converted with wxKanban"):
            # the '---' rule directly above the marker belongs to the block too
            while idx and set(body[idx - 1]) == {"-"}:
                idx -= 1
            return body[:idx]
    return body


def find_header_block(lines):
    """Index of the LAST line of the first run of >=3 field-dictionary header labels, or None."""
    stripped = [l.strip() for l in lines]
    i, n = 0, len(stripped)
    while i < n:
        if stripped[i] in HEADER_LABELS:
            j = i
            while j < n and stripped[j] in HEADER_LABELS:
                j += 1
            if j - i >= 3:
                return j - 1
            i = j
        else:
            i += 1
    return None


def strip_repeated_headers(body):
    """
    Remove the field-dictionary header block wherever it reappears inside the field list.

    A field list longer than one PDF page reprints the whole 8-column header on every later page,
    and the splitter emits one '## <subsection>' heading per source page, so a 2-page data file
    carries a second '## Data files and items' plus '<name> data file items' plus all 8 labels in
    the MIDDLE of the stream. Stripping only at the start of the body leaves them there.

    They do not simply get skipped as strays. None of the labels can satisfy match_type() on its
    own, so most are skipped one at a time — but the LAST one ('Default value') ends up close
    enough to the next real field's type line to be captured as that field's NAME, silently
    renaming a real column and losing its true name.

    A header label is only dropped as part of a RUN of them, never on its own. Several labels are
    ordinary English words ('Type', 'Size', 'Direction', 'Default value') and a real item may
    legitimately carry one as its caption; deleting those single lines would corrupt the very
    fields this is meant to protect. A reprint always emits the whole block in order, so a run is
    both sufficient to catch it and impossible for field data to produce by accident.

    Note: like the start-of-body anchor above, the 'data file items' test here is English-only.
    pcsoft-doc-split.py matches this same subsection across six locales; this step does not yet,
    so a non-English export is a known gap in BOTH places, not a regression introduced here.
    """
    MIN_RUN = 3
    out = []
    i, n = 0, len(body)
    while i < n:
        line = body[i]
        if line.startswith("## ") or line.lower().endswith("data file items"):
            i += 1
            continue
        if line in HEADER_LABELS:
            j = i
            while j < n and body[j] in HEADER_LABELS:
                j += 1
            if j - i >= MIN_RUN:
                i = j                        # reprinted header block -> drop the whole run
                continue
            out.extend(body[i:j])            # a lone label is real field content
            i = j
            continue
        out.append(line)
        i += 1
    return out


def parse_table(path, unmapped=None):
    name = os.path.basename(path).split(".")[0]
    lines = [l.rstrip() for l in open(path, encoding="utf-8").read().split("\n")]
    # body = lines after "<name> data file items" + the header labels
    start = next((i for i, l in enumerate(lines)
                  if l.strip().endswith("data file items")), None)
    if start is None:
        # Not every export prints that line. Some emit the field-dictionary header block directly
        # under the '## Data files and items' heading with no '<name> data file items' line at all
        # — and with the line as the ONLY anchor, those files returned zero fields. Silently: the
        # table still appeared in the run summary, and the generated DDL simply had no columns for
        # it. Verified on a real 211-table export where every single table parsed to nothing.
        # The header block itself is the more reliable anchor, so fall back to it.
        start = find_header_block(lines)
        if start is None:
            return name, []
    body = [l.strip() for l in lines[start + 1:] if l.strip()]
    body = drop_watermark_trailer(body)
    # Drop the leading header block. Each label appears exactly once in it, so a REPEAT means the
    # block has ended and we are looking at field data — which matters because 'Type', 'Size',
    # 'Caption' and 'Direction' are all plausible item names, and a table whose first item is one
    # of them had that item swallowed by an unbounded pop.
    seen = set()
    while body and body[0] in HEADER_LABELS and body[0] not in seen:
        seen.add(body.pop(0))
    body = strip_repeated_headers(body)

    fields = []
    i = 0
    n = len(body)
    while i < n:
        fname = body[i]
        if not ITEM_NAME_RE.match(fname):
            i += 1                       # not an item name -> note text, legend, stray
            continue
        # Locate this field's type line. The search starts at i+2, NOT i+1: this document family
        # always prints a caption line between the item name and its type (when the developer left
        # the caption empty PCSoft fills it with the name itself), so position i+1 is the caption by
        # construction and can never be the type.
        #
        # This is the fix for the widest desync shape. Captions are frequently type WORDS —
        # 'Date', 'Time', 'Currency', 'String' are ordinary English captions for date, time, money
        # and text columns. Taking the first type-looking line from i+1 matched the CAPTION, left
        # the real type line unconsumed, and that line then became the next field's name: a real
        # export produced items literally named 'Date (yyyymmdd)', 'Time (hhmm)' and 'String'.
        # Every one of those phantoms is a real column lost.
        j = i + 2
        while j < n and match_type(body[j])[0] is None and j - i <= 7:
            j += 1
        # Anything in the caption span that LOOKS like a type but is not one is an unmapped type
        # being absorbed as caption text. This must be checked whether or not a type was found
        # further down the window: when a later line does match, the unknown type is swallowed
        # silently AND the scan slides past the next field, so one unknown label both mistypes its
        # own column and deletes the following one.
        if unmapped is not None:
            for c in range(i + 1, min(j + 1, n)):
                cand = body[c]
                if match_type(cand)[0] is not None:
                    continue
                if SUSPECT_TYPE_RE.match(cand):
                    unmapped.append({"type": cand, "table": name, "field": fname})
                    continue
                # Second shape: a bare capitalized word followed by a size. 'Decimal' reached real
                # conversions this way — SUSPECT_TYPE_RE only knows the '<n>-byte <word>' family,
                # so a one-word unknown type was absorbed as caption text and never reported, and
                # the gate that exists to hard-stop on an unmapped type never fired.
                nxt = body[c + 1] if c + 1 < n else ""
                if (cand not in HEADER_LABELS and BARE_TYPE_RE.match(cand)
                        and NUMERIC_LINE_RE.match(nxt)):
                    unmapped.append({"type": cand, "table": name, "field": fname})

        if j >= n or match_type(body[j])[0] is None:
            # No type anywhere in the window. Today that just drops the field: the scan moves on
            # one line and the column never reaches the DDL. The line sitting in the TYPE position
            # is the most likely culprit, so report it rather than lose the column in silence —
            # this is what caught 'Character' and 'Array of 20 String' in real exports, neither of
            # which the shape-based patterns below can match.
            if unmapped is not None and i + 2 < n:
                cand = body[i + 2]
                # One unknown type desyncs the scan, so the NEXT window fails too and reports
                # whatever it finds — which is usually a caption. When the developer left the
                # caption empty PCSoft repeats the item name, so a candidate identical to the line
                # above it is a caption, not a type. Without this, one unknown type ('Array of 20
                # String') was reported as two, the second being a real column name.
                if cand != body[i + 1] and looks_like_type_label(cand):
                    unmapped.append({"type": cand, "table": name, "field": fname})
                    # Step over the whole record we just judged unreadable (name, caption, type)
                    # instead of one line. Advancing by one walks the scan back into the same
                    # record from its caption, and each pass reports something else it finds —
                    # turning one unknown type into a list of imaginary ones.
                    i += 3
                    continue
            i += 1
            continue
        caption = " ".join(body[i + 1:j]).strip()
        lbl, key = match_type(body[j])
        k = j + 1
        # consume 2-line type tails like "Automatic identifier (8 " + "bytes)"
        if k < n and body[k] in ("bytes)", "byte)"):
            k += 1
        # ...and the date/time FORMAT annotation, printed on its own line under the type label:
        #     Date and Time
        #     (yyyymmddhhmmssccc)
        # It is part of the type, so it is consumed here. Left behind it became the NEXT field's
        # name and shifted every field after it — once per Date/Time item, so a table with several
        # of them drifted several positions.
        if key in ("date", "time", "datetime") and k < n \
                and DATE_FORMAT_ANNOTATION_RE.match(body[k]):
            k += 1
        size = None
        default = None
        components = None

        # A composite key documents its own member columns on the line(s) after the type:
        #     Composite key:
        #     CustomerID+AddressType
        #     8
        # The list wraps mid-token at the PDF column width ("ProductID+StartDate+End" / "Date"),
        # so continuation lines are joined with no separator. Taking the members from HERE rather
        # than splitting the pseudo-item's name matters: that name is itself truncated by the
        # column width ("CustomerID_AddressTyp"), so it cannot be split back into real columns.
        if key == "composite":
            parts = []
            while k < n and not re.fullmatch(r"\d+", body[k]) and len(parts) < 6:
                parts.append(body[k])
                k += 1
            components = "".join(parts).strip()

        if k < n and re.fullmatch(r"\d+", body[k]) and (key in ("varchar", "uvarchar", "composite")):
            size = int(body[k]); k += 1
        # optional trailing default: a numeric whose following line is NOT a type.
        # Decimal defaults are printed in full ("0.000000" for a Currency item), so an
        # integers-only pattern left that line behind to be read as the next field's name.
        if k < n and re.fullmatch(r"-?\d+(?:[.,]\d+)?", body[k]):
            # Decide by POSITION, not by "is the very next line a type". If this number is a
            # default the next record starts one line later, so its type sits at k+3 and k+2 holds
            # a caption; if the number were itself the next field's NAME, the type would sit at
            # k+2. Asking about k+1 got this wrong whenever the following item was NAMED after a
            # type — a real export has an item called DateTime, and it cost the field before it
            # its default and the field after it its name.
            follower_is_type = k + 2 < n and match_type(body[k + 2])[0] is not None
            if not follower_is_type:
                default = body[k]; k += 1
        fields.append(dict(name=fname, caption=caption, hfsql=lbl, key=key,
                           size=size, default=default, components=components))
        i = k
    return name, fields


def declared_item_count(schema_path):
    """The item count the analysis states about itself ("Nb items"), or None if not found.

    The Analysis "General information" page prints its counts as a block of labels followed by a
    block of numbers in the same order:
        Generation # / Number of data files / Nb items / Nb links / Nb connections / Nb groups
        1 / 25 / 130 / 26 / 0 / 0
    "Nb items" counts DISTINCT item names across the analysis, not columns: an export declaring 130
    items parsed to 185 columns over 130 distinct names, because an item reused in several data
    files is one dictionary entry and several columns. Verified against a full real export.
    """
    if not os.path.exists(schema_path):
        return None
    lines = [l.strip() for l in open(schema_path, encoding="utf-8").read().split("\n") if l.strip()]
    for i, line in enumerate(lines):
        if not re.match(r"^generation\s*#", line, re.I):
            continue
        j = i
        while j < len(lines) and not re.fullmatch(r"\d+", lines[j]):
            j += 1
        nums = []
        while j < len(lines) and re.fullmatch(r"\d+", lines[j]):
            nums.append(int(lines[j]))
            j += 1
        if len(nums) >= 3:
            return nums[2]
    return None


def parse_links(schema_path):
    """Return list of (src_tbl, src_item, dst_tbl, dst_item) FK relationships."""
    txt = [l.strip() for l in open(schema_path, encoding="utf-8").read().split("\n")]
    links = []
    i = 0
    while i < len(txt):
        if txt[i] == "Data file" and i + 2 < len(txt):
            src_tbl, dst_tbl = txt[i + 1], txt[i + 2]
            # next "Item" then two item lines
            j = i + 3
            while j < len(txt) and txt[j] != "Item":
                j += 1
            if j + 2 < len(txt):
                src_item = re.sub(r"\s*\(.*\)$", "", txt[j + 1])
                dst_item = re.sub(r"\s*\(.*\)$", "", txt[j + 2])
                if re.match(r"^\w+$", src_tbl) and re.match(r"^\w+$", dst_tbl) \
                        and src_item and dst_item:
                    links.append((src_tbl, src_item, dst_tbl, dst_item))
            i = j + 1
        else:
            i += 1
    # dedupe
    seen, out = set(), []
    for l in links:
        if l not in seen:
            seen.add(l); out.append(l)
    return out


# ---------------------------------------------------------------------------
# Truncated item-name recovery
# ---------------------------------------------------------------------------
#
# The per-table pages print each item name into a fixed-width PDF column, and a name wider than
# that column is CUT: "CompanyBankAccountNo" arrives as "CompanyBankAccount". Nothing downstream
# can tell a cut name from a short one, so the DDL gets a plausible column with the WRONG name and
# every query later written against it is wrong. Reported from the field eight times before it was
# recognised as one defect, every time found by hand weeks after the conversion.
#
# Two other places in the same document print the name in a wider column and disagree with the
# table page exactly where it was cut:
#   * the analysis Item dictionary, a flat listing carrying "Used by..." — which data files use the
#     item — so a candidate can be tied to THIS table instead of merely existing somewhere;
#   * the UI control data bindings ("<DataFile>.<Item>"), which are not column-truncated at all.
#
# Neither is authoritative alone, which is why this is a gated repair and not a substitution. The
# field recommendation was to treat the dictionary as authoritative; measured over four real
# exports (642 tables) that alone proposes 254 renames that are WRONG, in two shapes: a genuine
# short column that merely prefixes a longer item ("BusinessPartner" -> "BusinessPartnerChargeCode")
# and the optimizer's composite-key entries, which are concatenations of member names and so prefix
# half the table. The gates below reduce that to zero renames on the two exports that have no
# truncation at all — the property that actually matters, since an export this stage already reads
# correctly must come out of it unchanged.

DICT_HEADER_LABELS = {"Item", "Type", "Size", "Unique Key", "Key with Duplicates",
                      "Used by...", "Analysis", "Item dictionary", "Caption"}

# Character slack between the longest name a document printed intact and the shortest one it could
# have cut. The column is measured in POINTS, not characters, so the cut lands in a BAND rather
# than at one length: a real export cuts between 19 and 23 characters depending on glyph widths.
# Anything shorter than (longest seen - band) demonstrably fitted, so it cannot be a casualty, and
# that single test is what removes the short-name false positives the dictionary invites.
TRUNCATION_BAND = 4

_BINDING_RE = re.compile(r"\b([A-Za-z_][A-Za-z0-9_]*)\.([A-Za-z_][A-Za-z0-9_]*)\b")


def parse_item_dictionary(schema_path, known_tables):
    """Map each Item-dictionary entry to the lower-cased data files that use it.

    The dictionary prints a name ONCE, then one "Type / Size / keys / <data file>" group per data
    file that uses it — the name is not reprinted for the second and later usages. Groups are
    therefore delimited by a known data-file name, and that is also what keeps an item NAMED after
    a type ("Date", "DateTime", "Caption") from vanishing: the name is whatever precedes a type
    inside a group, not whatever fails to look like one.
    """
    if not os.path.exists(schema_path):
        return {}
    tables_lc = {t.lower() for t in known_tables}
    items, cur, buf, in_dict = {}, None, [], False
    for raw in open(schema_path, encoding="utf-8").read().split("\n"):
        line = raw.strip()
        if not line:
            continue
        if line == "Item dictionary" or (line.startswith("#") and "Item dictionary" in line):
            in_dict, cur, buf = True, None, []
            continue
        if line.startswith("#"):
            in_dict = False
            continue
        if not in_dict or line in DICT_HEADER_LABELS:
            continue
        if line.lower() in tables_lc:
            if buf:
                if len(buf) >= 2 and match_type(buf[1])[0] is not None:
                    cur = buf[0]                       # name printed, even if type-shaped
                elif match_type(buf[0])[0] is None and buf[0] != "<Unused>":
                    cur = buf[0]
            if cur:
                items.setdefault(cur, set()).add(line.lower())
            buf = []
            continue
        buf.append(line)
    return items


def harvest_control_bindings(src_dir, known_tables):
    """Return {data file: {item names}} from "<DataFile>.<Item>" bindings on the non-table pages.

    A control's Data binding names the item in full — it is printed in a far wider column than the
    per-table field list — so where the two disagree on a prefix, this is the intact spelling. Only
    pages OTHER than the per-table extracts are read, so a truncated name cannot seed this oracle
    from the very pages it is meant to correct.
    """
    by_table, lookup = {}, {t.lower(): t for t in known_tables}
    for path in sorted(glob.glob(os.path.join(src_dir, "*.md"))):
        if path.endswith(".table.md"):
            continue
        try:
            text = open(path, encoding="utf-8", errors="replace").read()
        except OSError:
            continue
        for m in _BINDING_RE.finditer(text):
            table = lookup.get(m.group(1).lower())
            if table:
                by_table.setdefault(table, set()).add(m.group(2))
    return by_table


def recover_truncated_names(tables, src_dir):
    """Restore item names the per-table page cut at its column width, in place.

    Returns (applied, unresolved): applied is (table, cut, restored, oracle); unresolved is
    (table, cut, candidates, why). Unresolved is REPORTED, never guessed — swapping one wrong name
    for another wrong name is not a repair, and this parser's history is of confident corruption.
    """
    known = [t for t, _ in tables]
    dictionary = parse_item_dictionary(os.path.join(src_dir, "_schema.md"), known)
    bindings = harvest_control_bindings(src_dir, known)

    lengths = [len(f["name"]) for _, fl in tables for f in fl if f["key"] != "composite"]
    if not lengths:
        return [], []
    floor = max(lengths) - TRUNCATION_BAND

    # The dictionary is printed in a wider column, but it is a PDF column too and it cuts its own
    # longest entries. A candidate sitting at that width is itself suspect, so it is reported
    # instead of written into the DDL.
    dict_lengths = [len(k) for k in dictionary]
    dict_floor = (max(dict_lengths) - TRUNCATION_BAND) if dict_lengths else None

    applied, unresolved = [], []
    for tname, fields in tables:
        present = {f["name"].lower() for f in fields}
        bound_pool = bindings.get(tname, set())
        dict_pool = [k for k, used in dictionary.items() if tname.lower() in used]
        for f in fields:
            if f["key"] == "composite":
                continue
            name = f["name"]
            if len(name) < floor:
                continue

            def extend(pool):
                return sorted({c for c in pool
                               if c.lower().startswith(name.lower())
                               and len(c) > len(name)
                               and c.lower() not in present},
                              key=lambda c: (len(c), c))

            # The caption sits in a WIDER column on the very same row, and where it is a bare
            # identifier that extends the name, it is the name — no cross-referencing needed and
            # no ambiguity possible. This is also the only oracle that can separate several
            # columns the cut collapsed onto one string: one export has six distinct items all
            # printed as "mse_thoughtproduction", which emitted six identically named columns and
            # made the CREATE TABLE invalid SQL. Their captions differ, so the rows come apart.
            cap = (f.get("caption") or "").strip()
            if (len(cap) > len(name) and cap.lower().startswith(name.lower())
                    and ITEM_NAME_RE.match(cap) and cap.lower() not in present):
                f["name"] = cap
                present.add(cap.lower())
                applied.append((tname, name, cap, "row caption"))
                continue

            bound, from_dict = extend(bound_pool), extend(dict_pool)
            if len(bound) == 1:
                choice, oracle = bound[0], "control binding"
            elif bound:
                unresolved.append((tname, name, bound, "several bindings extend this name"))
                continue
            elif len(from_dict) == 1:
                choice, oracle = from_dict[0], "item dictionary"
                if dict_floor is not None and len(choice) >= dict_floor:
                    unresolved.append((tname, name, from_dict,
                                       "the dictionary entry is itself at its column width"))
                    continue
            elif from_dict:
                unresolved.append((tname, name, from_dict,
                                   "several dictionary items extend this name"))
                continue
            else:
                continue
            f["name"] = choice
            present.discard(name.lower())
            present.add(choice.lower())
            applied.append((tname, name, choice, oracle))
    return applied, unresolved


def apply_renames_to_links(links, applied):
    """Re-point FK endpoints at the restored column names.

    emit_ddl writes each link's item name straight into the ALTER TABLE, and never checks that the
    column exists — so renaming a column without this leaves a foreign key referencing a name that
    is no longer in the table, and the DDL fails at run time instead of at review.
    """
    remap = {(t.lower(), old.lower()): new for t, old, new, _ in applied}
    out = []
    for src_tbl, src_item, dst_tbl, dst_item in links:
        src_item = remap.get((src_tbl.lower(), src_item.lower()), src_item)
        dst_item = remap.get((dst_tbl.lower(), dst_item.lower()), dst_item)
        out.append((src_tbl, src_item, dst_tbl, dst_item))
    return out


def render_truncation_report(applied, unresolved):
    """Markdown sidecar listing every name restored and every one left alone."""
    out = ["# Item names cut by the PDF column", "",
           "The per-table pages print item names into a fixed-width column and cut the ones that "
           "do not fit. Names below were checked against the analysis Item dictionary "
           "(with its \"Used by...\" column) and the UI control data bindings.", ""]
    if applied:
        out += [f"## Restored ({len(applied)})", "",
                "These are already corrected in the generated DDL and ER diagram.", "",
                "| Data file | As printed | Restored to | Source |", "|---|---|---|---|"]
        out += [f"| {t} | `{old}` | `{new}` | {src} |" for t, old, new, src in sorted(applied)]
        out.append("")
    if unresolved:
        out += [f"## Left as printed ({len(unresolved)})", "",
                "These look cut, but the evidence was not conclusive, so the DDL keeps the name "
                "exactly as the PDF printed it. Check each against the source before building on "
                "it.", "",
                "| Data file | As printed | Possible full name(s) | Why not applied |",
                "|---|---|---|---|"]
        out += [f"| {t} | `{name}` | {', '.join('`%s`' % c for c in cands)} | {why} |"
                for t, name, cands, why in sorted(unresolved)]
        out.append("")
    return "\n".join(out) + "\n"


def col_type(f, dialect):
    tm = TYPEMAP[dialect]
    if f["key"] == "composite":
        return None  # composite key pseudo-item: not a real column
    if f["key"] not in tm:
        # This used to fall back to VARCHAR(255). A recognised HFSQL type that is missing from one
        # dialect's map would then emit a plausible column of the WRONG type — a number or a date
        # silently becoming text, which survives DDL review and corrupts the data load later.
        sys.exit(
            f"schema-to-sql: HFSQL type '{f['hfsql']}' (key '{f['key']}') has no {dialect} mapping.\n"
            f"  Field: {f['name']}\n"
            f"  Refusing to guess — a wrong column type is not visible in the generated DDL.\n"
            f"  Report this to wxKanban so the mapping ships for everyone."
        )
    t = tm[f["key"]]
    if "{n}" in t:
        t = t.format(n=f["size"] or 255)
    return t


def report_unmapped(unmapped, out_dir):
    """
    Stop the run, name every unknown type, and leave a payload for upstream.

    The operator knows what these types mean; the kit does not. So the run asks, applies the answer
    via --type-map, and files the confirmed mapping back to wxKanban so the built-in table grows and
    the next person converting the same kind of app never hits it. A conversion that quietly drops
    the columns instead teaches nobody anything.
    """
    by_type = {}
    for row in unmapped:
        by_type.setdefault(row["type"], []).append(f"{row['table']}.{row['field']}")

    print("", file=sys.stderr)
    print(f"schema-to-sql: {len(by_type)} unmapped HFSQL type(s) - these columns would be DROPPED:",
          file=sys.stderr)
    for label, where in sorted(by_type.items()):
        print(f"  {label}", file=sys.stderr)
        for w in where[:6]:
            print(f"      {w}", file=sys.stderr)
        if len(where) > 6:
            print(f"      ...and {len(where) - 6} more", file=sys.stderr)

    valid = sorted({k for dial in TYPEMAP.values() for k in dial})
    print("", file=sys.stderr)
    print("  Ask the developer what each type should become, then re-run with:", file=sys.stderr)
    for label in sorted(by_type):
        print(f'      --type-map "{label}=<key>"', file=sys.stderr)
    print(f"  Valid keys: {', '.join(valid)}", file=sys.stderr)

    payload = {
        "kind": "hfsql-unmapped-types",
        "types": [{"label": lbl, "occurrences": len(w), "examples": w[:10]}
                  for lbl, w in sorted(by_type.items())],
    }
    try:
        os.makedirs(out_dir, exist_ok=True)
        path = os.path.join(out_dir, "_unmapped-types.json")
        with open(path, "w", encoding="utf-8") as fh:
            json.dump(payload, fh, indent=2)
        print(f"  Details written to {path}", file=sys.stderr)
        print("  Once confirmed, file the mapping to wxKanban (project_submit_feedback) so it "
              "ships in the built-in table.", file=sys.stderr)
    except OSError as err:
        print(f"  (could not write _unmapped-types.json: {err})", file=sys.stderr)
    return 3


# Identifier rules per dialect: the quoting pair, and the maximum identifier length.
# Firebird 3 caps identifiers at 31 characters — a generated FK name easily exceeds that, and the
# DDL then fails at execution time, after the developer has already accepted the schema.
IDENT_RULES = {
    "firebird": ('"', '"', 31),
    "postgres": ('"', '"', 63),
    "mssql": ("[", "]", 128),
    "mysql": ("`", "`", 64),
}

# Quote only when the bare form would not survive. Blanket quoting would change case semantics for
# every existing conversion (Postgres and Firebird fold unquoted names), so plain ASCII names are
# left exactly as they are today.
_BARE_IDENT_RE = re.compile(r"^[A-Za-z_][A-Za-z0-9_]*$")

# Words that would parse as syntax rather than a name. Not exhaustive per dialect — the common
# ones a legacy schema actually collides with.
_RESERVED = {
    "user", "order", "group", "table", "index", "key", "select", "from", "where", "check",
    "default", "primary", "foreign", "references", "column", "value", "values", "date", "time",
    "timestamp", "year", "month", "day", "level", "size", "type", "status", "language", "position",
}


def quote_ident(name, dialect):
    """Quote an identifier when the bare form would break or change meaning."""
    open_q, close_q, _ = IDENT_RULES[dialect]
    needs = (not _BARE_IDENT_RE.match(name or "")) or (name or "").lower() in _RESERVED
    if not needs:
        return name
    # An embedded closing quote would end the identifier early; double it, which every dialect here
    # accepts for its own quote character.
    escaped = (name or "").replace(close_q, close_q * 2)
    return f"{open_q}{escaped}{close_q}"


def constraint_name(prefix, parts, dialect, used=None):
    """
    Build a constraint/index name that fits the dialect's identifier limit.

    Accented and non-ASCII characters are folded to ASCII rather than quoted: a constraint name is
    ours to choose, and keeping it plain avoids quoting rules differing across the four targets.
    When the name must be shortened, a short deterministic suffix keeps it unique so two long
    tables do not collide on a truncated name.
    """
    _, _, maxlen = IDENT_RULES[dialect]
    folded = unicodedata.normalize("NFKD", "_".join([prefix, *parts]))
    ascii_name = "".join(c for c in folded if not unicodedata.combining(c))
    ascii_name = re.sub(r"[^A-Za-z0-9_]", "_", ascii_name).strip("_") or prefix

    if len(ascii_name) > maxlen:
        digest = hashlib.sha1(ascii_name.encode("utf-8")).hexdigest()[:6]
        ascii_name = f"{ascii_name[:maxlen - 7].rstrip('_')}_{digest}"

    if used is not None:
        base, n = ascii_name, 2
        while ascii_name in used:
            suffix = f"_{n}"
            ascii_name = f"{base[:maxlen - len(suffix)]}{suffix}"
            n += 1
        used.add(ascii_name)
    return ascii_name


def emit_indexes(tname, fields, composites, dialect, used_names):
    """
    One index per HFSQL composite key, on its real member columns.

    Non-unique by design: the export cannot tell us which keys are unique (see the file header), and
    an index that should have been UNIQUE is a missing constraint, while a UNIQUE that should not
    have been is a failed data load. The first is recoverable at review; the second is discovered by
    the customer.
    """
    if not composites:
        return []
    known = {f["name"] for f in fields if f["key"] != "composite"}
    out = []
    for f in composites:
        members = [m.strip() for m in (f.get("components") or "").split("+") if m.strip()]
        caption = f.get("caption") or ""
        optimizer = "optimizer" in caption.lower()
        if not members:
            out.append(f"-- REVIEW {tname}: composite key {f['name']} - member columns unreadable "
                       f"in the export, index NOT generated")
            continue
        unknown = [m for m in members if m not in known]
        cols = ", ".join(quote_ident(m, dialect) for m in members)
        idx = constraint_name("IDX", [tname, *members], dialect, used_names)
        stmt = f"CREATE INDEX {idx} ON {quote_ident(tname, dialect)} ({cols});"
        if unknown:
            # Emitted commented-out rather than dropped: a member naming no column means the parse
            # missed something, and silently omitting the index would hide that.
            out.append(f"-- REVIEW {tname}: member(s) {', '.join(unknown)} match no column - "
                       f"check the export, then enable:")
            out.append(f"-- {stmt}")
        else:
            if optimizer:
                out.append("-- optimizer-added key (HFSQL query-plan artifact) - keep only if the "
                           "rebuilt app queries this way")
            out.append(stmt)
    return out


def emit_ddl(tables, links, dialect):
    out = [f"-- Firebird-ready DDL is dialect={dialect}. Generated from the HFSQL analysis.",
           "-- Names and types kept FAITHFUL (1:1) per the conversion choice.",
           "-- HFSQL composite keys are emitted as NON-UNIQUE indexes below each table.",
           "--",
           "-- REVIEW REQUIRED - two things this file cannot know:",
           "--   1. Uniqueness. HFSQL marks Unique Key / Key with Duplicates with a check glyph that",
           "--      does not survive PDF text extraction, so NO single-column key is recoverable and",
           "--      no composite key's uniqueness is either. Promote to UNIQUE by hand where the",
           "--      business rule genuinely requires it - guessing here breaks the data load on rows",
           "--      the legacy app allowed.",
           "--   2. Whether each index is still worth carrying. Ones captioned 'added by the",
           "--      optimizer' are HFSQL query-plan artifacts, marked as such below.",
           "-- HFSQL has no unsigned/boolean parity on every target - verify edge cases.", ""]
    ident_clause = {
        "firebird": " GENERATED BY DEFAULT AS IDENTITY", "postgres": " GENERATED BY DEFAULT AS IDENTITY",
        "mssql": " IDENTITY(1,1)", "mysql": " AUTO_INCREMENT",
    }[dialect]
    used_names = set()          # constraint names must be unique after length-truncation
    for tname, fields in tables:
        out.append(f"CREATE TABLE {quote_ident(tname, dialect)} (")
        cols, notes, pk = [], [], None     # cols get commas; notes are comment-only lines
        composites = []                    # HFSQL composite keys -> indexes, below
        for f in fields:
            ct = col_type(f, dialect)
            if ct is None:                  # composite-key pseudo-item -> index, emitted below
                composites.append(f)
                continue
            coldef = f"{quote_ident(f['name'], dialect)} {ct}"
            if f["key"] == "identifier":
                coldef += ident_clause
                pk = f["name"]
            if f["default"] is not None and f["key"] in ("boolean", "int4", "int8",
                                                          "uint4", "uint1"):
                coldef += f" DEFAULT {f['default']}"
            cols.append((coldef, f["caption"]))
        if pk:
            pkname = constraint_name("PK", [tname], dialect, used_names)
            cols.append((f"CONSTRAINT {pkname} PRIMARY KEY ({quote_ident(pk, dialect)})", ""))
        lines = []
        for idx, (coldef, cap) in enumerate(cols):
            comma = "," if idx < len(cols) - 1 else ""
            cmt = f"  -- {cap}" if cap else ""
            lines.append(f"  {coldef}{comma}{cmt}")
        out.extend(notes)
        out.append("\n".join(lines))
        out.append(");")
        out.extend(emit_indexes(tname, fields, composites, dialect, used_names))
        out.append("")
    out.append("-- ---- Foreign keys (from the analysis Links) ----")
    valid = {t for t, _ in tables}
    for src_tbl, src_item, dst_tbl, dst_item in links:
        if dst_tbl in valid and src_tbl in valid:
            fkname = constraint_name("FK", [dst_tbl, src_tbl, dst_item], dialect, used_names)
            out.append(f"ALTER TABLE {quote_ident(dst_tbl, dialect)} ADD CONSTRAINT {fkname} "
                       f"FOREIGN KEY ({quote_ident(dst_item, dialect)}) "
                       f"REFERENCES {quote_ident(src_tbl, dialect)} ({quote_ident(src_item, dialect)});")
    return "\n".join(out) + "\n"


def emit_er(tables, links, dialect):
    out = ["# WW_Newsletter — Database (ER diagram & field reference)", "",
           f"_Generated from the HFSQL analysis. Target dialect: **{dialect}**. "
           f"Field names/types kept faithful (1:1)._", "",
           "## Entity-relationship diagram", "", "```mermaid", "erDiagram"]
    valid = {t for t, _ in tables}
    for src_tbl, src_item, dst_tbl, dst_item in links:
        if src_tbl in valid and dst_tbl in valid:
            out.append(f"    {src_tbl} ||--o{{ {dst_tbl} : \"{dst_item}\"")
    out.append("```")
    out.append("\n## Tables\n")
    for tname, fields in tables:
        out.append(f"### {tname}\n")
        out.append("| Column | HFSQL type | Size | Target type | Caption |")
        out.append("|---|---|---|---|---|")
        for f in fields:
            ct = col_type(f, dialect) or "*(composite key)*"
            out.append(f"| {f['name']} | {f['hfsql']} | {f['size'] or ''} | {ct} | {f['caption']} |")
        out.append("")
    out.append(MIGRATION_NOTE)
    return "\n".join(out) + "\n"


MIGRATION_NOTE = """## Migrating the data out of HFSQL

The source data lives in **HFSQL** (`.fic`/`.ndx`/`.mmo` files) which the target DB cannot read
directly. To move the data you must **export it from the WinDev side as JSON first**:

> **Action required (developer):** write a small **WLanguage global procedure** in the legacy app
> that loops every in-scope data file (`HReadFirst`/`HReadNext`) and serializes each record to
> **JSON** (e.g. one JSON array per table, or NDJSON), then drop the files somewhere we can read.
> A loader then reads that JSON and inserts into the target DB using the DDL in this folder.

Migration checklist for the loader step:
- Encoding: HFSQL strings are often Windows-1252 → convert to **UTF-8**.
- Empty-date sentinels (`0000-00-00`, `18991230`) → **NULL**.
- Booleans may serialize as `0/1` or `"True"/"False"` — normalize.
- French decimal comma → dot for numeric columns.
- Load order must respect FKs (parents before children).
- Binary memos/images (BLOB columns) — export as base64 in the JSON, or to files + store a path.
"""


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--dialect", default="firebird", choices=list(TYPEMAP))
    ap.add_argument("--src", default="pre-convert")
    ap.add_argument("--out", default="rebuild/db")
    ap.add_argument("--type-map", action="append", metavar="LABEL=KEY",
                    help='Map an HFSQL type this kit does not know, e.g. --type-map "2-byte integer=int2". '
                         'Repeatable. Report confirmed mappings to wxKanban so they ship built in.')
    rd.add_redaction_args(ap, scan=False)
    args = ap.parse_args()

    register_type_overrides(args.type_map)

    state = rd.RedactionState()
    table_files = sorted(glob.glob(os.path.join(args.src, "*.table.md")))
    if not table_files:
        sys.exit(f"schema-to-sql: no *.table.md under {args.src}. Nothing to convert — "
                 "run the splitter first, and check it reported the tables it wrote.")

    unmapped = []
    tables = [parse_table(p, unmapped) for p in table_files]
    if unmapped:
        return report_unmapped(unmapped, args.out)

    # A data file that parsed to zero columns is not a real result. Reaching the DDL stage with an
    # empty table means the parse missed the item block, and an empty CREATE TABLE reads as
    # "this table has no columns" rather than "we failed to read it".
    empty = [t for t, f in tables if not f]
    if empty:
        sys.exit(f"schema-to-sql: {len(empty)} data file(s) parsed to zero columns: "
                 f"{', '.join(empty[:8])}{' …' if len(empty) > 8 else ''}\n"
                 "  The item block was not recognised. Refusing to emit empty tables.")

    # Restore item names the per-table page cut at its column width, before anything downstream
    # sees them: the DDL, the ER diagram and the distinct-name reconciliation must all agree, and
    # a name corrected afterwards would leave the foreign keys pointing at the cut spelling.
    renamed, unresolved_names = recover_truncated_names(tables, args.src)

    links = parse_links(os.path.join(args.src, "_schema.md"))
    if renamed:
        links = apply_renames_to_links(links, renamed)

    os.makedirs(args.out, exist_ok=True)
    sql_path = os.path.join(args.out, f"schema.{args.dialect}.sql")
    er_path = os.path.join(args.out, "ER-diagram.md")
    # [SCOPE 125 / T009] Emission goes through the shared funnel (FR-007): it redacts, accumulates
    # findings and stamps the watermark on .md, so the manual stamp_markdown call that used to wrap
    # the ER diagram is gone rather than duplicated.
    rd.write_text(sql_path, emit_ddl(tables, links, args.dialect), state)
    rd.write_text(er_path, emit_er(tables, links, args.dialect), state)

    nfields = sum(len(f) for _, f in tables)
    print(f"dialect={args.dialect}  tables={len(tables)}  fields={nfields}  links={len(links)}")
    print(f"  -> {sql_path}")
    print(f"  -> {er_path}")
    for t, f in tables:
        print(f"    {t}: {len(f)} fields")

    # Reconcile against the analysis's own declared item count. Field loss in this parser has
    # always been SILENT — the run prints a summary and exits 0 whether it read every column or
    # two thirds of them — and every field-reported instance was found by a developer reading the
    # DDL against the source weeks later. This is the same self-check the splitter already does
    # for its data-file count, one stage further down.
    #
    # Reported, not enforced. The count reconciles exactly on some exports and not on others, and
    # a shortfall can equally mean the SPLITTER dropped a page upstream (its per-table extract is
    # then short before this parser ever sees it). Until that is separated, exiting non-zero here
    # would block conversions this stage did nothing wrong in. A visible number the developer can
    # act on is the honest version.
    declared = declared_item_count(os.path.join(args.src, "_schema.md"))
    if declared:
        distinct = len({f["name"] for _, fl in tables for f in fl})
        if distinct < declared:
            print(f"  !! INCOMPLETE: the analysis declares {declared} items; this run recovered "
                  f"{distinct} distinct item names ({declared - distinct} short).")
            print("     Columns are missing from the generated DDL. Check the source PDF for the "
                  "affected tables before building on this schema, and report the shortfall.")
        else:
            print(f"  items: {distinct} distinct / {declared} declared by the analysis")

    if renamed or unresolved_names:
        trunc_path = os.path.join(args.out, "truncated-names.md")
        rd.write_text(trunc_path, render_truncation_report(renamed, unresolved_names), state)
        if renamed:
            print(f"  names restored: {len(renamed)} item name(s) were cut by the PDF column and "
                  f"have been restored from the analysis.")
        if unresolved_names:
            print(f"  !! {len(unresolved_names)} further name(s) look cut but could not be "
                  f"resolved safely; the DDL keeps them exactly as printed.")
        print(f"  -> {trunc_path}")

    # A cut can collapse two different items onto the same string, and two columns of one name is
    # not merely untidy — the CREATE TABLE will not run. Recovery separates almost all of them;
    # what survives is named here rather than discovered when the DDL is executed.
    collided = []
    for tname, fields in tables:
        seen = {}
        for f in fields:
            if f["key"] != "composite":
                seen[f["name"].lower()] = seen.get(f["name"].lower(), 0) + 1
        collided += [(tname, n) for n, c in seen.items() if c > 1]
    if collided:
        print(f"  !! {len(collided)} column name(s) appear TWICE in their table, because the cut "
              f"collapsed distinct items onto one name - this DDL will not run as written:")
        for tname, n in collided[:8]:
            print(f"       {tname}.{n}")

    sidecar_path = os.path.join(args.out, rd.SIDECAR_NAME)
    if state.findings:
        rd.write_text(sidecar_path, rd.render_sidecar(state), state)
    print(rd.summary_line(state, sidecar_path))
    return rd.exit_code(len(state.findings), args.fail_on_secrets)


if __name__ == "__main__":
    sys.exit(main())
