#!/usr/bin/env python3
"""
pcsoft-schema-to-sql.py - Generate DDL + an ER diagram from a converted PCSoft HFSQL analysis.

Input : pre-convert/*.table.md  (one per data file) and pre-convert/_schema.md (Links section).
Output: rebuild/db/schema.<dialect>.sql  - faithful DDL (names/types kept 1:1)
        rebuild/db/ER-diagram.md          - Mermaid erDiagram + per-table field docs + migration notes

Field names and types are kept verbatim (the "Keep as-is / faithful" choice). The HFSQL type is
mapped to the nearest target type without renaming or restructuring anything.

Usage:
    python scripts/pcsoft-schema-to-sql.py --dialect firebird --out rebuild/db
"""
import argparse
import json
import hashlib
import unicodedata
import sys
import glob
import os
import re

import os as _wmos, sys as _wmsys
_wmsys.path.insert(0, _wmos.path.dirname(_wmos.path.abspath(__file__)))
import wxconv_redact as rd  # noqa: E402 - the watermark stamp now lives inside rd.write_text()

# HFSQL type -> target type, per dialect. (col_type, is_identity_pk)
TYPEMAP = {
    "firebird": {
        "uint2": "INTEGER", "float4": "FLOAT",
        "identifier": "BIGINT",            # + GENERATED BY DEFAULT AS IDENTITY (Firebird 3+)
        "int8": "BIGINT", "int4": "INTEGER", "uint4": "BIGINT", "uint1": "INTEGER",
        "varchar": "VARCHAR({n})", "uvarchar": "VARCHAR({n})",
        "text": "BLOB SUB_TYPE TEXT", "blob": "BLOB SUB_TYPE BINARY",
        "boolean": "BOOLEAN", "date": "DATE", "time": "TIME", "datetime": "TIMESTAMP",
        "numeric": "NUMERIC(18,4)", "double": "DOUBLE PRECISION",
    },
    "postgres": {
        "uint2": "INTEGER", "float4": "REAL",
        "identifier": "BIGINT", "int8": "BIGINT", "int4": "INTEGER", "uint4": "BIGINT",
        "uint1": "INTEGER", "varchar": "VARCHAR({n})", "uvarchar": "VARCHAR({n})",
        "text": "TEXT", "blob": "BYTEA", "boolean": "BOOLEAN", "date": "DATE",
        "time": "TIME", "datetime": "TIMESTAMPTZ", "numeric": "NUMERIC(18,4)",
        "double": "DOUBLE PRECISION",
    },
    "mssql": {
        "uint2": "INT", "float4": "REAL",
        "identifier": "BIGINT", "int8": "BIGINT", "int4": "INT", "uint4": "BIGINT",
        "uint1": "INT", "varchar": "NVARCHAR({n})", "uvarchar": "NVARCHAR({n})",
        "text": "NVARCHAR(MAX)", "blob": "VARBINARY(MAX)", "boolean": "TINYINT", "date": "DATE",
        "time": "TIME", "datetime": "DATETIME2", "numeric": "DECIMAL(18,4)",
        "double": "FLOAT",
    },
    "mysql": {
        "uint2": "INT UNSIGNED", "float4": "FLOAT",
        "identifier": "BIGINT", "int8": "BIGINT", "int4": "INT", "uint4": "INT UNSIGNED",
        "uint1": "INT", "varchar": "VARCHAR({n})", "uvarchar": "VARCHAR({n})",
        "text": "LONGTEXT", "blob": "LONGBLOB", "boolean": "TINYINT(1)", "date": "DATE",
        "time": "TIME", "datetime": "DATETIME", "numeric": "DECIMAL(18,4)", "double": "DOUBLE",
    },
}

# HFSQL type label (as it appears in the doc) -> internal key. Order matters (longest first).
HFSQL = [
    ("Automatic identifier", "identifier"),
    ("Unsigned 4-byte integer", "uint4"),
    ("Unsigned 2-byte integer", "uint2"),
    ("Unsigned 1-byte integer", "uint1"),
    ("8-byte integer", "int8"),
    ("4-byte integer", "int4"),
    ("4-byte real", "float4"),
    ("8-byte real", "double"),
    ("Unicode Text Memo", "text"),
    ("Unicode string", "uvarchar"),
    ("Other binary memo", "blob"),
    ("Image (binary memo)", "blob"),
    ("Binary memo", "blob"),
    ("Text Memo", "text"),
    ("Memo", "text"),
    ("Composite key", "composite"),
    ("Boolean", "boolean"),
    ("Date and Time", "datetime"),
    ("DateTime", "datetime"),
    ("Date", "date"),
    ("Time", "time"),
    ("Currency", "numeric"),
    ("Monetary", "numeric"),
    ("Numeric", "numeric"),
    ("Real", "double"),
    ("Double", "double"),
    ("String", "varchar"),
]
TYPE_STARTS = [lbl for lbl, _ in HFSQL]

HEADER_LABELS = {"Caption", "Type", "Size", "Unique Key", "Key with Duplicates",
                 "Direction", "Default value"}


# "<n>-byte integer" / "<n>-byte real" is a WIDTH, not a distinct type, so it does not need a table
# entry or a human to interpret it — PCSoft emits widths this kit has never seen (2, 6, ...) and the
# right answer is always "the smallest target integer that holds n bytes". Deriving it means an
# unseen width converts correctly instead of stopping the run; only a genuinely unknown WORD
# ("6-byte duration") still needs asking about.
BYTE_TYPE_RE = re.compile(r"^(unsigned\s+)?(\d+)-byte\s+(integer|int|real|float)\b", re.I)

# Integers land on exactly TWO target types: INTEGER and BIGINT. In practice HFSQL emits 4- and
# 8-byte integers, and anything narrower (1-, 2-byte) is widened to INTEGER rather than given its
# own SMALLINT/TINYINT. Widening is always safe and keeps the converted schema from sprouting
# narrow types the application never needed; narrowing never is, so nothing rounds down.
_SIGNED_WIDTHS = ((4, "int4"), (8, "int8"))
_UNSIGNED_WIDTHS = ((2, "int4"), (4, "uint4"))   # unsigned 4-byte needs BIGINT to hold its range
_WIDEST_INT = "int8"                              # anything above 8 bytes still lands on BIGINT


def derive_byte_type(label):
    """Map an '<n>-byte integer/real' label to a key by width. None if not that shape."""
    m = BYTE_TYPE_RE.match(label)
    if not m:
        return None
    unsigned, nbytes, family = bool(m.group(1)), int(m.group(2)), m.group(3).lower()

    if family in ("real", "float"):
        # 4 bytes is single precision; anything wider gets double. Never narrow a float.
        return "float4" if nbytes <= 4 else "double"

    widths = _UNSIGNED_WIDTHS if unsigned else _SIGNED_WIDTHS
    for width, key in widths:
        if nbytes <= width:
            return key
    return _WIDEST_INT


# WinDev's optimizer adds its own composite keys, and their CAPTION reads "Composite key added by
# the optimizer" — which starts with a real type label. Matched as a type it consumes the caption
# line, and the actual "Composite key:" line below is then swallowed into the member-column list.
# The caption is worth keeping intact anyway: it is what distinguishes an optimizer index from a
# business key when the developer reviews which ones to carry over.
_CAPTION_NOT_TYPE_RE = re.compile(r"^Composite key\s+added\b", re.I)


def match_type(line):
    if _CAPTION_NOT_TYPE_RE.match(line or ""):
        return None, None
    for lbl, key in HFSQL:
        if line.startswith(lbl):
            return lbl, key
    derived = derive_byte_type(line)
    if derived:
        # Report the label as written in the doc, so the DDL comment stays faithful to the source.
        return line.split("(")[0].strip(), derived
    return None, None


# A line sitting in the TYPE position that we could not map. Deliberately narrow: the "<n>-byte
# <word>" family is what the field reports hit ("2-byte integer", "4-byte real") and no field
# caption realistically reads that way, so this can hard-stop a run without false positives.
# An unmapped type is not a cosmetic gap — the field is dropped from the DDL entirely, so the
# column silently disappears from the converted schema.
SUSPECT_TYPE_RE = re.compile(r"^(unsigned\s+)?\d+-byte\s+[a-z]+", re.I)


def register_type_overrides(pairs):
    """
    Apply --type-map "<HFSQL label>=<key>" overrides supplied by the operator.

    This is how a conversion gets unblocked the moment the developer says what an unknown type
    means, instead of waiting for a kit release. The same answer is then reported for upstream
    inclusion so the next person never sees it (see report_unmapped).
    """
    valid = set()
    for dial in TYPEMAP.values():
        valid.update(dial)
    for raw in pairs or []:
        if "=" not in raw:
            sys.exit(f"--type-map expects '<HFSQL label>=<key>', got: {raw}")
        label, key = (p.strip() for p in raw.split("=", 1))
        if not label or not key:
            sys.exit(f"--type-map expects '<HFSQL label>=<key>', got: {raw}")
        if key not in valid:
            sys.exit(
                f"--type-map: unknown key '{key}'.\n"
                f"  Valid keys: {', '.join(sorted(valid))}\n"
                f"  Pick the closest existing key; if none fits, report the type to wxKanban."
            )
        HFSQL.append((label, key))
    # match_type walks in order and uses startswith, so longest labels must be tried first or
    # "4-byte integer" would be shadowed by a shorter prefix.
    HFSQL.sort(key=lambda pair: len(pair[0]), reverse=True)


def parse_table(path, unmapped=None):
    name = os.path.basename(path).split(".")[0]
    lines = [l.rstrip() for l in open(path, encoding="utf-8").read().split("\n")]
    # body = lines after "<name> data file items" + the 7 header labels
    try:
        start = next(i for i, l in enumerate(lines)
                     if l.strip().endswith("data file items"))
    except StopIteration:
        return name, []
    body = [l.strip() for l in lines[start + 1:] if l.strip()]
    # drop leading header labels
    while body and body[0] in HEADER_LABELS:
        body.pop(0)

    fields = []
    i = 0
    n = len(body)
    while i < n:
        fname = body[i]
        # locate this field's type line within a small window (caption may be multi-line)
        j = i + 1
        while j < n and match_type(body[j])[0] is None and j - i <= 6:
            j += 1
        # Anything in the caption span that LOOKS like a type but is not one is an unmapped type
        # being absorbed as caption text. This must be checked whether or not a type was found
        # further down the window: when a later line does match, the unknown type is swallowed
        # silently AND the scan slides past the next field, so one unknown label both mistypes its
        # own column and deletes the following one.
        if unmapped is not None:
            for cand in body[i + 1:min(j + 1, n)]:
                if SUSPECT_TYPE_RE.match(cand) and match_type(cand)[0] is None:
                    unmapped.append({"type": cand, "table": name, "field": fname})

        if j >= n or match_type(body[j])[0] is None:
            i += 1                       # no type found near here -> stray line, skip
            continue
        caption = " ".join(body[i + 1:j]).strip()
        lbl, key = match_type(body[j])
        k = j + 1
        # consume 2-line type tails like "Automatic identifier (8 " + "bytes)"
        if k < n and body[k] in ("bytes)", "byte)"):
            k += 1
        size = None
        default = None
        components = None

        # A composite key documents its own member columns on the line(s) after the type:
        #     Composite key:
        #     CustomerID+AddressType
        #     8
        # The list wraps mid-token at the PDF column width ("ProductID+StartDate+End" / "Date"),
        # so continuation lines are joined with no separator. Taking the members from HERE rather
        # than splitting the pseudo-item's name matters: that name is itself truncated by the
        # column width ("CustomerID_AddressTyp"), so it cannot be split back into real columns.
        if key == "composite":
            parts = []
            while k < n and not re.fullmatch(r"\d+", body[k]) and len(parts) < 6:
                parts.append(body[k])
                k += 1
            components = "".join(parts).strip()

        if k < n and re.fullmatch(r"\d+", body[k]) and (key in ("varchar", "uvarchar", "composite")):
            size = int(body[k]); k += 1
        # optional trailing default: a numeric whose following line is NOT a type
        if k < n and re.fullmatch(r"-?\d+", body[k]):
            nxt = body[k + 1] if k + 1 < n else ""
            if match_type(nxt)[0] is None:
                default = body[k]; k += 1
        fields.append(dict(name=fname, caption=caption, hfsql=lbl, key=key,
                           size=size, default=default, components=components))
        i = k
    return name, fields


def parse_links(schema_path):
    """Return list of (src_tbl, src_item, dst_tbl, dst_item) FK relationships."""
    txt = [l.strip() for l in open(schema_path, encoding="utf-8").read().split("\n")]
    links = []
    i = 0
    while i < len(txt):
        if txt[i] == "Data file" and i + 2 < len(txt):
            src_tbl, dst_tbl = txt[i + 1], txt[i + 2]
            # next "Item" then two item lines
            j = i + 3
            while j < len(txt) and txt[j] != "Item":
                j += 1
            if j + 2 < len(txt):
                src_item = re.sub(r"\s*\(.*\)$", "", txt[j + 1])
                dst_item = re.sub(r"\s*\(.*\)$", "", txt[j + 2])
                if re.match(r"^\w+$", src_tbl) and re.match(r"^\w+$", dst_tbl) \
                        and src_item and dst_item:
                    links.append((src_tbl, src_item, dst_tbl, dst_item))
            i = j + 1
        else:
            i += 1
    # dedupe
    seen, out = set(), []
    for l in links:
        if l not in seen:
            seen.add(l); out.append(l)
    return out


def col_type(f, dialect):
    tm = TYPEMAP[dialect]
    if f["key"] == "composite":
        return None  # composite key pseudo-item: not a real column
    if f["key"] not in tm:
        # This used to fall back to VARCHAR(255). A recognised HFSQL type that is missing from one
        # dialect's map would then emit a plausible column of the WRONG type — a number or a date
        # silently becoming text, which survives DDL review and corrupts the data load later.
        sys.exit(
            f"schema-to-sql: HFSQL type '{f['hfsql']}' (key '{f['key']}') has no {dialect} mapping.\n"
            f"  Field: {f['name']}\n"
            f"  Refusing to guess — a wrong column type is not visible in the generated DDL.\n"
            f"  Report this to wxKanban so the mapping ships for everyone."
        )
    t = tm[f["key"]]
    if "{n}" in t:
        t = t.format(n=f["size"] or 255)
    return t


def report_unmapped(unmapped, out_dir):
    """
    Stop the run, name every unknown type, and leave a payload for upstream.

    The operator knows what these types mean; the kit does not. So the run asks, applies the answer
    via --type-map, and files the confirmed mapping back to wxKanban so the built-in table grows and
    the next person converting the same kind of app never hits it. A conversion that quietly drops
    the columns instead teaches nobody anything.
    """
    by_type = {}
    for row in unmapped:
        by_type.setdefault(row["type"], []).append(f"{row['table']}.{row['field']}")

    print("", file=sys.stderr)
    print(f"schema-to-sql: {len(by_type)} unmapped HFSQL type(s) - these columns would be DROPPED:",
          file=sys.stderr)
    for label, where in sorted(by_type.items()):
        print(f"  {label}", file=sys.stderr)
        for w in where[:6]:
            print(f"      {w}", file=sys.stderr)
        if len(where) > 6:
            print(f"      ...and {len(where) - 6} more", file=sys.stderr)

    valid = sorted({k for dial in TYPEMAP.values() for k in dial})
    print("", file=sys.stderr)
    print("  Ask the developer what each type should become, then re-run with:", file=sys.stderr)
    for label in sorted(by_type):
        print(f'      --type-map "{label}=<key>"', file=sys.stderr)
    print(f"  Valid keys: {', '.join(valid)}", file=sys.stderr)

    payload = {
        "kind": "hfsql-unmapped-types",
        "types": [{"label": lbl, "occurrences": len(w), "examples": w[:10]}
                  for lbl, w in sorted(by_type.items())],
    }
    try:
        os.makedirs(out_dir, exist_ok=True)
        path = os.path.join(out_dir, "_unmapped-types.json")
        with open(path, "w", encoding="utf-8") as fh:
            json.dump(payload, fh, indent=2)
        print(f"  Details written to {path}", file=sys.stderr)
        print("  Once confirmed, file the mapping to wxKanban (project_submit_feedback) so it "
              "ships in the built-in table.", file=sys.stderr)
    except OSError as err:
        print(f"  (could not write _unmapped-types.json: {err})", file=sys.stderr)
    return 3


# Identifier rules per dialect: the quoting pair, and the maximum identifier length.
# Firebird 3 caps identifiers at 31 characters — a generated FK name easily exceeds that, and the
# DDL then fails at execution time, after the developer has already accepted the schema.
IDENT_RULES = {
    "firebird": ('"', '"', 31),
    "postgres": ('"', '"', 63),
    "mssql": ("[", "]", 128),
    "mysql": ("`", "`", 64),
}

# Quote only when the bare form would not survive. Blanket quoting would change case semantics for
# every existing conversion (Postgres and Firebird fold unquoted names), so plain ASCII names are
# left exactly as they are today.
_BARE_IDENT_RE = re.compile(r"^[A-Za-z_][A-Za-z0-9_]*$")

# Words that would parse as syntax rather than a name. Not exhaustive per dialect — the common
# ones a legacy schema actually collides with.
_RESERVED = {
    "user", "order", "group", "table", "index", "key", "select", "from", "where", "check",
    "default", "primary", "foreign", "references", "column", "value", "values", "date", "time",
    "timestamp", "year", "month", "day", "level", "size", "type", "status", "language", "position",
}


def quote_ident(name, dialect):
    """Quote an identifier when the bare form would break or change meaning."""
    open_q, close_q, _ = IDENT_RULES[dialect]
    needs = (not _BARE_IDENT_RE.match(name or "")) or (name or "").lower() in _RESERVED
    if not needs:
        return name
    # An embedded closing quote would end the identifier early; double it, which every dialect here
    # accepts for its own quote character.
    escaped = (name or "").replace(close_q, close_q * 2)
    return f"{open_q}{escaped}{close_q}"


def constraint_name(prefix, parts, dialect, used=None):
    """
    Build a constraint/index name that fits the dialect's identifier limit.

    Accented and non-ASCII characters are folded to ASCII rather than quoted: a constraint name is
    ours to choose, and keeping it plain avoids quoting rules differing across the four targets.
    When the name must be shortened, a short deterministic suffix keeps it unique so two long
    tables do not collide on a truncated name.
    """
    _, _, maxlen = IDENT_RULES[dialect]
    folded = unicodedata.normalize("NFKD", "_".join([prefix, *parts]))
    ascii_name = "".join(c for c in folded if not unicodedata.combining(c))
    ascii_name = re.sub(r"[^A-Za-z0-9_]", "_", ascii_name).strip("_") or prefix

    if len(ascii_name) > maxlen:
        digest = hashlib.sha1(ascii_name.encode("utf-8")).hexdigest()[:6]
        ascii_name = f"{ascii_name[:maxlen - 7].rstrip('_')}_{digest}"

    if used is not None:
        base, n = ascii_name, 2
        while ascii_name in used:
            suffix = f"_{n}"
            ascii_name = f"{base[:maxlen - len(suffix)]}{suffix}"
            n += 1
        used.add(ascii_name)
    return ascii_name


def emit_indexes(tname, fields, composites, dialect, used_names):
    """
    One index per HFSQL composite key, on its real member columns.

    Non-unique by design: the export cannot tell us which keys are unique (see the file header), and
    an index that should have been UNIQUE is a missing constraint, while a UNIQUE that should not
    have been is a failed data load. The first is recoverable at review; the second is discovered by
    the customer.
    """
    if not composites:
        return []
    known = {f["name"] for f in fields if f["key"] != "composite"}
    out = []
    for f in composites:
        members = [m.strip() for m in (f.get("components") or "").split("+") if m.strip()]
        caption = f.get("caption") or ""
        optimizer = "optimizer" in caption.lower()
        if not members:
            out.append(f"-- REVIEW {tname}: composite key {f['name']} - member columns unreadable "
                       f"in the export, index NOT generated")
            continue
        unknown = [m for m in members if m not in known]
        cols = ", ".join(quote_ident(m, dialect) for m in members)
        idx = constraint_name("IDX", [tname, *members], dialect, used_names)
        stmt = f"CREATE INDEX {idx} ON {quote_ident(tname, dialect)} ({cols});"
        if unknown:
            # Emitted commented-out rather than dropped: a member naming no column means the parse
            # missed something, and silently omitting the index would hide that.
            out.append(f"-- REVIEW {tname}: member(s) {', '.join(unknown)} match no column - "
                       f"check the export, then enable:")
            out.append(f"-- {stmt}")
        else:
            if optimizer:
                out.append("-- optimizer-added key (HFSQL query-plan artifact) - keep only if the "
                           "rebuilt app queries this way")
            out.append(stmt)
    return out


def emit_ddl(tables, links, dialect):
    out = [f"-- Firebird-ready DDL is dialect={dialect}. Generated from the HFSQL analysis.",
           "-- Names and types kept FAITHFUL (1:1) per the conversion choice.",
           "-- HFSQL composite keys are emitted as NON-UNIQUE indexes below each table.",
           "--",
           "-- REVIEW REQUIRED - two things this file cannot know:",
           "--   1. Uniqueness. HFSQL marks Unique Key / Key with Duplicates with a check glyph that",
           "--      does not survive PDF text extraction, so NO single-column key is recoverable and",
           "--      no composite key's uniqueness is either. Promote to UNIQUE by hand where the",
           "--      business rule genuinely requires it - guessing here breaks the data load on rows",
           "--      the legacy app allowed.",
           "--   2. Whether each index is still worth carrying. Ones captioned 'added by the",
           "--      optimizer' are HFSQL query-plan artifacts, marked as such below.",
           "-- HFSQL has no unsigned/boolean parity on every target - verify edge cases.", ""]
    ident_clause = {
        "firebird": " GENERATED BY DEFAULT AS IDENTITY", "postgres": " GENERATED BY DEFAULT AS IDENTITY",
        "mssql": " IDENTITY(1,1)", "mysql": " AUTO_INCREMENT",
    }[dialect]
    used_names = set()          # constraint names must be unique after length-truncation
    for tname, fields in tables:
        out.append(f"CREATE TABLE {quote_ident(tname, dialect)} (")
        cols, notes, pk = [], [], None     # cols get commas; notes are comment-only lines
        composites = []                    # HFSQL composite keys -> indexes, below
        for f in fields:
            ct = col_type(f, dialect)
            if ct is None:                  # composite-key pseudo-item -> index, emitted below
                composites.append(f)
                continue
            coldef = f"{quote_ident(f['name'], dialect)} {ct}"
            if f["key"] == "identifier":
                coldef += ident_clause
                pk = f["name"]
            if f["default"] is not None and f["key"] in ("boolean", "int4", "int8",
                                                          "uint4", "uint1"):
                coldef += f" DEFAULT {f['default']}"
            cols.append((coldef, f["caption"]))
        if pk:
            pkname = constraint_name("PK", [tname], dialect, used_names)
            cols.append((f"CONSTRAINT {pkname} PRIMARY KEY ({quote_ident(pk, dialect)})", ""))
        lines = []
        for idx, (coldef, cap) in enumerate(cols):
            comma = "," if idx < len(cols) - 1 else ""
            cmt = f"  -- {cap}" if cap else ""
            lines.append(f"  {coldef}{comma}{cmt}")
        out.extend(notes)
        out.append("\n".join(lines))
        out.append(");")
        out.extend(emit_indexes(tname, fields, composites, dialect, used_names))
        out.append("")
    out.append("-- ---- Foreign keys (from the analysis Links) ----")
    valid = {t for t, _ in tables}
    for src_tbl, src_item, dst_tbl, dst_item in links:
        if dst_tbl in valid and src_tbl in valid:
            fkname = constraint_name("FK", [dst_tbl, src_tbl, dst_item], dialect, used_names)
            out.append(f"ALTER TABLE {quote_ident(dst_tbl, dialect)} ADD CONSTRAINT {fkname} "
                       f"FOREIGN KEY ({quote_ident(dst_item, dialect)}) "
                       f"REFERENCES {quote_ident(src_tbl, dialect)} ({quote_ident(src_item, dialect)});")
    return "\n".join(out) + "\n"


def emit_er(tables, links, dialect):
    out = ["# WW_Newsletter — Database (ER diagram & field reference)", "",
           f"_Generated from the HFSQL analysis. Target dialect: **{dialect}**. "
           f"Field names/types kept faithful (1:1)._", "",
           "## Entity-relationship diagram", "", "```mermaid", "erDiagram"]
    valid = {t for t, _ in tables}
    for src_tbl, src_item, dst_tbl, dst_item in links:
        if src_tbl in valid and dst_tbl in valid:
            out.append(f"    {src_tbl} ||--o{{ {dst_tbl} : \"{dst_item}\"")
    out.append("```")
    out.append("\n## Tables\n")
    for tname, fields in tables:
        out.append(f"### {tname}\n")
        out.append("| Column | HFSQL type | Size | Target type | Caption |")
        out.append("|---|---|---|---|---|")
        for f in fields:
            ct = col_type(f, dialect) or "*(composite key)*"
            out.append(f"| {f['name']} | {f['hfsql']} | {f['size'] or ''} | {ct} | {f['caption']} |")
        out.append("")
    out.append(MIGRATION_NOTE)
    return "\n".join(out) + "\n"


MIGRATION_NOTE = """## Migrating the data out of HFSQL

The source data lives in **HFSQL** (`.fic`/`.ndx`/`.mmo` files) which the target DB cannot read
directly. To move the data you must **export it from the WinDev side as JSON first**:

> **Action required (developer):** write a small **WLanguage global procedure** in the legacy app
> that loops every in-scope data file (`HReadFirst`/`HReadNext`) and serializes each record to
> **JSON** (e.g. one JSON array per table, or NDJSON), then drop the files somewhere we can read.
> A loader then reads that JSON and inserts into the target DB using the DDL in this folder.

Migration checklist for the loader step:
- Encoding: HFSQL strings are often Windows-1252 → convert to **UTF-8**.
- Empty-date sentinels (`0000-00-00`, `18991230`) → **NULL**.
- Booleans may serialize as `0/1` or `"True"/"False"` — normalize.
- French decimal comma → dot for numeric columns.
- Load order must respect FKs (parents before children).
- Binary memos/images (BLOB columns) — export as base64 in the JSON, or to files + store a path.
"""


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--dialect", default="firebird", choices=list(TYPEMAP))
    ap.add_argument("--src", default="pre-convert")
    ap.add_argument("--out", default="rebuild/db")
    ap.add_argument("--type-map", action="append", metavar="LABEL=KEY",
                    help='Map an HFSQL type this kit does not know, e.g. --type-map "2-byte integer=int2". '
                         'Repeatable. Report confirmed mappings to wxKanban so they ship built in.')
    rd.add_redaction_args(ap, scan=False)
    args = ap.parse_args()

    register_type_overrides(args.type_map)

    state = rd.RedactionState()
    table_files = sorted(glob.glob(os.path.join(args.src, "*.table.md")))
    if not table_files:
        sys.exit(f"schema-to-sql: no *.table.md under {args.src}. Nothing to convert — "
                 "run the splitter first, and check it reported the tables it wrote.")

    unmapped = []
    tables = [parse_table(p, unmapped) for p in table_files]
    if unmapped:
        return report_unmapped(unmapped, args.out)

    # A data file that parsed to zero columns is not a real result. Reaching the DDL stage with an
    # empty table means the parse missed the item block, and an empty CREATE TABLE reads as
    # "this table has no columns" rather than "we failed to read it".
    empty = [t for t, f in tables if not f]
    if empty:
        sys.exit(f"schema-to-sql: {len(empty)} data file(s) parsed to zero columns: "
                 f"{', '.join(empty[:8])}{' …' if len(empty) > 8 else ''}\n"
                 "  The item block was not recognised. Refusing to emit empty tables.")

    links = parse_links(os.path.join(args.src, "_schema.md"))

    os.makedirs(args.out, exist_ok=True)
    sql_path = os.path.join(args.out, f"schema.{args.dialect}.sql")
    er_path = os.path.join(args.out, "ER-diagram.md")
    # [SCOPE 125 / T009] Emission goes through the shared funnel (FR-007): it redacts, accumulates
    # findings and stamps the watermark on .md, so the manual stamp_markdown call that used to wrap
    # the ER diagram is gone rather than duplicated.
    rd.write_text(sql_path, emit_ddl(tables, links, args.dialect), state)
    rd.write_text(er_path, emit_er(tables, links, args.dialect), state)

    nfields = sum(len(f) for _, f in tables)
    print(f"dialect={args.dialect}  tables={len(tables)}  fields={nfields}  links={len(links)}")
    print(f"  -> {sql_path}")
    print(f"  -> {er_path}")
    for t, f in tables:
        print(f"    {t}: {len(f)} fields")

    sidecar_path = os.path.join(args.out, rd.SIDECAR_NAME)
    if state.findings:
        rd.write_text(sidecar_path, rd.render_sidecar(state), state)
    print(rd.summary_line(state, sidecar_path))
    return rd.exit_code(len(state.findings), args.fail_on_secrets)


if __name__ == "__main__":
    sys.exit(main())
