#!/usr/bin/env python3
"""
pcsoft-schema-to-sql.py - Generate DDL + an ER diagram from a converted PCSoft HFSQL analysis.

Input : pre-convert/*.table.md  (one per data file) and pre-convert/_schema.md (Links section).
Output: rebuild/db/schema.<dialect>.sql  - faithful DDL (names/types kept 1:1)
        rebuild/db/ER-diagram.md          - Mermaid erDiagram + per-table field docs + migration notes

Field names and types are kept verbatim (the "Keep as-is / faithful" choice). The HFSQL type is
mapped to the nearest target type without renaming or restructuring anything.

Usage:
    python scripts/pcsoft-schema-to-sql.py --dialect firebird --out rebuild/db
"""
import argparse
import glob
import os
import re

import os as _wmos, sys as _wmsys
_wmsys.path.insert(0, _wmos.path.dirname(_wmos.path.abspath(__file__)))
from wxkanban_watermark import stamp_markdown

# HFSQL type -> target type, per dialect. (col_type, is_identity_pk)
TYPEMAP = {
    "firebird": {
        "identifier": "BIGINT",            # + GENERATED BY DEFAULT AS IDENTITY (Firebird 3+)
        "int8": "BIGINT", "int4": "INTEGER", "uint4": "INTEGER", "uint1": "SMALLINT",
        "varchar": "VARCHAR({n})", "uvarchar": "VARCHAR({n})",
        "text": "BLOB SUB_TYPE TEXT", "blob": "BLOB SUB_TYPE BINARY",
        "boolean": "BOOLEAN", "date": "DATE", "time": "TIME", "datetime": "TIMESTAMP",
        "numeric": "NUMERIC(18,4)", "double": "DOUBLE PRECISION",
    },
    "postgres": {
        "identifier": "BIGINT", "int8": "BIGINT", "int4": "INTEGER", "uint4": "BIGINT",
        "uint1": "SMALLINT", "varchar": "VARCHAR({n})", "uvarchar": "VARCHAR({n})",
        "text": "TEXT", "blob": "BYTEA", "boolean": "BOOLEAN", "date": "DATE",
        "time": "TIME", "datetime": "TIMESTAMPTZ", "numeric": "NUMERIC(18,4)",
        "double": "DOUBLE PRECISION",
    },
    "mssql": {
        "identifier": "BIGINT", "int8": "BIGINT", "int4": "INT", "uint4": "BIGINT",
        "uint1": "TINYINT", "varchar": "NVARCHAR({n})", "uvarchar": "NVARCHAR({n})",
        "text": "NVARCHAR(MAX)", "blob": "VARBINARY(MAX)", "boolean": "BIT", "date": "DATE",
        "time": "TIME", "datetime": "DATETIME2", "numeric": "DECIMAL(18,4)",
        "double": "FLOAT",
    },
    "mysql": {
        "identifier": "BIGINT", "int8": "BIGINT", "int4": "INT", "uint4": "INT UNSIGNED",
        "uint1": "TINYINT UNSIGNED", "varchar": "VARCHAR({n})", "uvarchar": "VARCHAR({n})",
        "text": "LONGTEXT", "blob": "LONGBLOB", "boolean": "TINYINT(1)", "date": "DATE",
        "time": "TIME", "datetime": "DATETIME", "numeric": "DECIMAL(18,4)", "double": "DOUBLE",
    },
}

# HFSQL type label (as it appears in the doc) -> internal key. Order matters (longest first).
HFSQL = [
    ("Automatic identifier", "identifier"),
    ("Unsigned 4-byte integer", "uint4"),
    ("Unsigned 1-byte integer", "uint1"),
    ("8-byte integer", "int8"),
    ("4-byte integer", "int4"),
    ("Unicode Text Memo", "text"),
    ("Unicode string", "uvarchar"),
    ("Other binary memo", "blob"),
    ("Image (binary memo)", "blob"),
    ("Binary memo", "blob"),
    ("Text Memo", "text"),
    ("Memo", "text"),
    ("Composite key", "composite"),
    ("Boolean", "boolean"),
    ("Date and Time", "datetime"),
    ("DateTime", "datetime"),
    ("Date", "date"),
    ("Time", "time"),
    ("Currency", "numeric"),
    ("Monetary", "numeric"),
    ("Numeric", "numeric"),
    ("Real", "double"),
    ("Double", "double"),
    ("String", "varchar"),
]
TYPE_STARTS = [lbl for lbl, _ in HFSQL]

HEADER_LABELS = {"Caption", "Type", "Size", "Unique Key", "Key with Duplicates",
                 "Direction", "Default value"}


def match_type(line):
    for lbl, key in HFSQL:
        if line.startswith(lbl):
            return lbl, key
    return None, None


def parse_table(path):
    name = os.path.basename(path).split(".")[0]
    lines = [l.rstrip() for l in open(path, encoding="utf-8").read().split("\n")]
    # body = lines after "<name> data file items" + the 7 header labels
    try:
        start = next(i for i, l in enumerate(lines)
                     if l.strip().endswith("data file items"))
    except StopIteration:
        return name, []
    body = [l.strip() for l in lines[start + 1:] if l.strip()]
    # drop leading header labels
    while body and body[0] in HEADER_LABELS:
        body.pop(0)

    fields = []
    i = 0
    n = len(body)
    while i < n:
        fname = body[i]
        # locate this field's type line within a small window (caption may be multi-line)
        j = i + 1
        while j < n and match_type(body[j])[0] is None and j - i <= 6:
            j += 1
        if j >= n or match_type(body[j])[0] is None:
            i += 1                       # no type found near here -> stray line, skip
            continue
        caption = " ".join(body[i + 1:j]).strip()
        lbl, key = match_type(body[j])
        k = j + 1
        # consume 2-line type tails like "Automatic identifier (8 " + "bytes)"
        if k < n and body[k] in ("bytes)", "byte)"):
            k += 1
        size = None
        default = None
        if key in ("varchar", "uvarchar") and k < n and re.fullmatch(r"\d+", body[k]):
            size = int(body[k]); k += 1
        # optional trailing default: a numeric whose following line is NOT a type
        if k < n and re.fullmatch(r"-?\d+", body[k]):
            nxt = body[k + 1] if k + 1 < n else ""
            if match_type(nxt)[0] is None:
                default = body[k]; k += 1
        fields.append(dict(name=fname, caption=caption, hfsql=lbl, key=key,
                           size=size, default=default))
        i = k
    return name, fields


def parse_links(schema_path):
    """Return list of (src_tbl, src_item, dst_tbl, dst_item) FK relationships."""
    txt = [l.strip() for l in open(schema_path, encoding="utf-8").read().split("\n")]
    links = []
    i = 0
    while i < len(txt):
        if txt[i] == "Data file" and i + 2 < len(txt):
            src_tbl, dst_tbl = txt[i + 1], txt[i + 2]
            # next "Item" then two item lines
            j = i + 3
            while j < len(txt) and txt[j] != "Item":
                j += 1
            if j + 2 < len(txt):
                src_item = re.sub(r"\s*\(.*\)$", "", txt[j + 1])
                dst_item = re.sub(r"\s*\(.*\)$", "", txt[j + 2])
                if re.match(r"^\w+$", src_tbl) and re.match(r"^\w+$", dst_tbl) \
                        and src_item and dst_item:
                    links.append((src_tbl, src_item, dst_tbl, dst_item))
            i = j + 1
        else:
            i += 1
    # dedupe
    seen, out = set(), []
    for l in links:
        if l not in seen:
            seen.add(l); out.append(l)
    return out


def col_type(f, dialect):
    tm = TYPEMAP[dialect]
    if f["key"] == "composite":
        return None  # composite key pseudo-item: not a real column
    t = tm.get(f["key"], "VARCHAR(255)")
    if "{n}" in t:
        t = t.format(n=f["size"] or 255)
    return t


def emit_ddl(tables, links, dialect):
    out = [f"-- Firebird-ready DDL is dialect={dialect}. Generated from the HFSQL analysis.",
           "-- Names and types kept FAITHFUL (1:1) per the conversion choice.",
           "-- Composite-key items are emitted as comments; review junction-table PKs.",
           "-- HFSQL has no unsigned/boolean parity on every target — verify edge cases.", ""]
    ident_clause = {
        "firebird": " GENERATED BY DEFAULT AS IDENTITY", "postgres": " GENERATED BY DEFAULT AS IDENTITY",
        "mssql": " IDENTITY(1,1)", "mysql": " AUTO_INCREMENT",
    }[dialect]
    for tname, fields in tables:
        out.append(f"CREATE TABLE {tname} (")
        cols, notes, pk = [], [], None     # cols get commas; notes are comment-only lines
        for f in fields:
            ct = col_type(f, dialect)
            if ct is None:                  # composite-key pseudo-item -> comment only
                notes.append(f"  -- {f['name']}: composite key ({f['caption']})")
                continue
            coldef = f"{f['name']} {ct}"
            if f["key"] == "identifier":
                coldef += ident_clause
                pk = f["name"]
            if f["default"] is not None and f["key"] in ("boolean", "int4", "int8",
                                                          "uint4", "uint1"):
                coldef += f" DEFAULT {f['default']}"
            cols.append((coldef, f["caption"]))
        if pk:
            cols.append((f"CONSTRAINT PK_{tname} PRIMARY KEY ({pk})", ""))
        lines = []
        for idx, (coldef, cap) in enumerate(cols):
            comma = "," if idx < len(cols) - 1 else ""
            cmt = f"  -- {cap}" if cap else ""
            lines.append(f"  {coldef}{comma}{cmt}")
        out.extend(notes)
        out.append("\n".join(lines))
        out.append(");\n")
    out.append("-- ---- Foreign keys (from the analysis Links) ----")
    valid = {t for t, _ in tables}
    for src_tbl, src_item, dst_tbl, dst_item in links:
        if dst_tbl in valid and src_tbl in valid:
            out.append(f"ALTER TABLE {dst_tbl} ADD CONSTRAINT FK_{dst_tbl}_{src_tbl}_{dst_item} "
                       f"FOREIGN KEY ({dst_item}) REFERENCES {src_tbl} ({src_item});")
    return "\n".join(out) + "\n"


def emit_er(tables, links, dialect):
    out = ["# WW_Newsletter — Database (ER diagram & field reference)", "",
           f"_Generated from the HFSQL analysis. Target dialect: **{dialect}**. "
           f"Field names/types kept faithful (1:1)._", "",
           "## Entity-relationship diagram", "", "```mermaid", "erDiagram"]
    valid = {t for t, _ in tables}
    for src_tbl, src_item, dst_tbl, dst_item in links:
        if src_tbl in valid and dst_tbl in valid:
            out.append(f"    {src_tbl} ||--o{{ {dst_tbl} : \"{dst_item}\"")
    out.append("```")
    out.append("\n## Tables\n")
    for tname, fields in tables:
        out.append(f"### {tname}\n")
        out.append("| Column | HFSQL type | Size | Target type | Caption |")
        out.append("|---|---|---|---|---|")
        for f in fields:
            ct = col_type(f, dialect) or "*(composite key)*"
            out.append(f"| {f['name']} | {f['hfsql']} | {f['size'] or ''} | {ct} | {f['caption']} |")
        out.append("")
    out.append(MIGRATION_NOTE)
    return "\n".join(out) + "\n"


MIGRATION_NOTE = """## Migrating the data out of HFSQL

The source data lives in **HFSQL** (`.fic`/`.ndx`/`.mmo` files) which the target DB cannot read
directly. To move the data you must **export it from the WinDev side as JSON first**:

> **Action required (developer):** write a small **WLanguage global procedure** in the legacy app
> that loops every in-scope data file (`HReadFirst`/`HReadNext`) and serializes each record to
> **JSON** (e.g. one JSON array per table, or NDJSON), then drop the files somewhere we can read.
> A loader then reads that JSON and inserts into the target DB using the DDL in this folder.

Migration checklist for the loader step:
- Encoding: HFSQL strings are often Windows-1252 → convert to **UTF-8**.
- Empty-date sentinels (`0000-00-00`, `18991230`) → **NULL**.
- Booleans may serialize as `0/1` or `"True"/"False"` — normalize.
- French decimal comma → dot for numeric columns.
- Load order must respect FKs (parents before children).
- Binary memos/images (BLOB columns) — export as base64 in the JSON, or to files + store a path.
"""


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--dialect", default="firebird", choices=list(TYPEMAP))
    ap.add_argument("--src", default="pre-convert")
    ap.add_argument("--out", default="rebuild/db")
    args = ap.parse_args()

    table_files = sorted(glob.glob(os.path.join(args.src, "*.table.md")))
    tables = [parse_table(p) for p in table_files]
    links = parse_links(os.path.join(args.src, "_schema.md"))

    os.makedirs(args.out, exist_ok=True)
    sql_path = os.path.join(args.out, f"schema.{args.dialect}.sql")
    er_path = os.path.join(args.out, "ER-diagram.md")
    open(sql_path, "w", encoding="utf-8").write(emit_ddl(tables, links, args.dialect))
    open(er_path, "w", encoding="utf-8").write(
        stamp_markdown(emit_er(tables, links, args.dialect), kind="converted", generator="wxConversion"))

    nfields = sum(len(f) for _, f in tables)
    print(f"dialect={args.dialect}  tables={len(tables)}  fields={nfields}  links={len(links)}")
    print(f"  -> {sql_path}")
    print(f"  -> {er_path}")
    for t, f in tables:
        print(f"    {t}: {len(f)} fields")


if __name__ == "__main__":
    main()
