#!/usr/bin/env python3
"""
clarion-reports-to-stub.py - Document every Clarion REPORT as ONE rebuild stub.

Input : pre-convert/*.report.md  (each embeds the verbatim REPORT ... END + procedure source in
        ```clarion fences).
Output: rebuild/scopes/RPT-reports-stub.md

Per report: page/paper format, bands present (HEADER/DETAIL/FOOTER/BREAK/FORM), the data source the
print loop walks (VIEW/FILE via SET/NEXT/Process), and referenced files. Clarion reports are band
layouts driven by a print loop, so this is a STUB: move print-time data assembly into an API/server
data-prep step, then render with a React PDF/print component (@react-pdf/renderer or a print-CSS
route; barcodes via bwip-js/jsbarcode).

Usage:
    python scripts/clarion-reports-to-stub.py --src pre-convert --out rebuild/scopes
"""
import argparse
import glob
import os
import re

import os as _wmos, sys as _wmsys
_wmsys.path.insert(0, _wmos.path.dirname(_wmos.path.abspath(__file__)))
from wxkanban_watermark import stamp_markdown

FENCE_RE = re.compile(r"```clarion\n(.*?)```", re.S)
BANDS = ["FORM", "PAGEHEADER", "HEADER", "DETAIL", "BREAK", "FOOTER", "PAGEFOOTER"]


def fences(path):
    return FENCE_RE.findall(open(path, encoding="utf-8").read())


def paren(text, name):
    m = re.search(rf"\b{name}\s*\(([^)]*)\)", text, re.I)
    return m.group(1).strip() if m else None


def analyze(text):
    bands = [b for b in BANDS if re.search(rf"^\s*{b}\b", text, re.I | re.M)]
    paper = paren(text, "PAPER") or paren(text, "AT")
    # data source: a VIEW(...) or the file walked by SET/NEXT/Process(view)
    src = paren(text, "VIEW")
    if not src:
        m = re.search(r"\bProcess\s*\(\s*([A-Za-z_]\w*)", text, re.I) \
            or re.search(r"\bSET\s*\(\s*([A-Za-z_:]\w*)", text, re.I)
        src = m.group(1) if m else None
    files = sorted(set(re.findall(r"\b([A-Za-z_]\w*):(?:Next|Fetch|Open|Update)", text, re.I)))
    return dict(bands=bands, paper=paper, src=src, files=files)


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--src", default="pre-convert")
    ap.add_argument("--out", default="rebuild/scopes")
    args = ap.parse_args()

    reports = sorted(glob.glob(os.path.join(args.src, "*.report.md")))
    out = ["# Reports rebuild stub (Clarion REPORT structures)", "",
           "_Generated by cwConversion. Each Clarion report is a band layout driven by a print loop. "
           "Rebuild target: assemble the data in an **API/server data-prep step**, then render with "
           "`@react-pdf/renderer` or a print-CSS route (barcodes via `bwip-js`/`jsbarcode`)._", ""]
    for path in reports:
        name = os.path.basename(path).split(".")[0]
        a = analyze("\n".join(fences(path)))
        out.append(f"## {name}")
        out.append("")
        out.append(f"- **Page/paper:** `{a['paper'] or '?'}`")
        out.append(f"- **Bands:** {', '.join(a['bands']) or '(none detected)'}")
        out.append(f"- **Data source:** `{a['src'] or '?'}`")
        if a["files"]:
            out.append(f"- **Files referenced:** {', '.join(f'`{f}`' for f in a['files'])}")
        out.append("- **Rebuild target:** server data-prep endpoint → React PDF/print component.")
        out.append("")

    if not reports:
        out.append("_No REPORT structures found in the source — nothing to stub._")

    os.makedirs(args.out, exist_ok=True)
    dest = os.path.join(args.out, "RPT-reports-stub.md")
    open(dest, "w", encoding="utf-8").write(
        stamp_markdown("\n".join(out) + "\n", kind='converted', generator='cwConversion'))
    print(f"reports={len(reports)}")
    print(f"  -> {dest}")


if __name__ == "__main__":
    main()
