import * as fs from 'fs';
import * as path from 'path';
import { handleCreateSpecs } from '../core/orchestrator/command-handlers/createspecs';

const SCOPE_PATH = path.resolve(process.cwd(), 'specs/Project-Scope/025-project-overview-builder.md');

const tasks = [
	// G1 — Database Schema
	{ title: 'T001: Create overviewdrafts Drizzle schema + migration', description: 'Add src/db/schema/overviewdrafts.ts with all 8 columns (id uuid v7, projectid FK nullable, proposalid FK nullable, authoruserid FK, companyid FK, status text w/ check constraint for draft|submitted|accepted|rejected, content text, createdat, updatedat). Run npm run db:generate. Migration reviewable and reversible independently.', priority: 'high', status: 'todo' },
	{ title: 'T002: Create overviewtranscripts Drizzle schema + migration', description: 'Add src/db/schema/overviewtranscripts.ts with all 6 columns incl. sourceuri text NULL (populated only for FR-014 imports). FK overviewdraftid cascade deletes. role enum user|assistant|system. sectionkey nullable.', priority: 'high', status: 'todo' },
	{ title: 'T003: Create importcache Drizzle schema + migration', description: 'Add src/db/schema/importcache.ts with (id, sourceuri, companyid FK, content text, contenthash text, fetchedat). Unique index on (sourceuri, companyid) for tenant isolation per C14. No FK to drafts — cache persists across drafts.', priority: 'high', status: 'todo' },
	{ title: 'T004: Schema validation tests (Vitest + test Postgres)', description: 'Insert/update/delete on each new table. Unique (sourceuri, companyid) fires on duplicate. FK cascade deletes transcripts when draft deleted. Status check constraint rejects invalid values. Run against ephemeral test DB.', priority: 'high', status: 'todo' },

	// G2 — Shared Utilities
	{ title: 'T005: Shared BA persona prompt module', description: 'Create src/server/ai/prompts/business-analyst.ts exporting BUSINESS_ANALYST_PROMPT plus six-section probe helpers. Imported by BOTH A4 (ai-message route) AND wxkanban-agent/core/orchestrator/command-handlers/buildscope.ts — divergence is a defect per Success Criterion #7. Unit test asserts single-source import.', priority: 'high', status: 'todo' },
	{ title: 'T006: Atomic file+DB persistence utility', description: 'Extend existing ProjectDocumentService with ProjectOverview doctype support. saveOverview(projectid, content) writes projectoverview.md at repo root AND upserts projectdocuments row transactionally (FR-007). On file-write failure: DB not updated. On DB failure: file reverted to pre-save content. Mirrors existing projectlifecycle.md sync pattern.', priority: 'high', status: 'todo' },
	{ title: 'T007: URL fetcher with host allowlist + DNS-rebind defense (C14 SSRF guard)', description: 'Create src/server/services/UrlImportService.ts. fetchAllowedUrl(url) checks hostname against allowlist (github.com, raw.githubusercontent.com, gist.github.com, gitlab.com, bitbucket.org, docs.google.com, notion.so), DNS-resolves and rejects RFC1918/loopback/link-local/cloud-metadata (169.254.169.254, fd00::/8, fe80::/10) IPs, 10s timeout, 500k response cap. Unit tests cover each rejection path including DNS-rebind.', priority: 'high', status: 'todo' },
	{ title: 'T008: Text chunking utility with 80-call hard cap', description: 'Create src/server/ai/text-chunker.ts. chunk(text, 8000) returns 8k windows with ~200 char overlap at sentence boundaries. analyzeWithChunking(chunks, sectionMapper) runs accumulating-context mode (N9): chunk N receives section-mapping-so-far from 1..N-1. Enforces 80 AI-call cap per import (prevents runaway cost on near-ceiling docs).', priority: 'high', status: 'todo' },

	// G3 — Backend Routes
	{ title: 'T009: POST /api/overview/draft — Create (A1)', description: 'Accept { mode: proposal|project }. Create overviewdrafts row, seed six-section template. Return { draftid, content }. JWT required; authoruserid + companyid from token. Integration tests: both modes, unauth 401.', priority: 'high', status: 'todo' },
	{ title: 'T010: GET /api/overview/draft/:id — Load (A2)', description: 'Return { content, transcript[], binding, status }. Authz: author OR admin OR consultant on same company. Integration tests: author 200, other user 403, admin any-company 200, consultant same-company 200.', priority: 'high', status: 'todo' },
	{ title: 'T011: PUT /api/overview/draft/:id — Save with atomic persistence + concurrent-save race (A3, N3)', description: 'Use T006 atomic persistence. For proposal-bound drafts: file NOT written until acceptance. For project-bound drafts: file written on Create Project (T017). Optimistic-lock via updatedat CAS (N3). Reject post-accept edits (FR-011 AC3). Integration tests: happy path, file-write failure rolls back DB, concurrent-save stale error, post-accept rejection.', priority: 'high', status: 'todo' },
	{ title: 'T012: POST /api/overview/draft/:id/ai-message — SSE BA interview (A4, N4)', description: 'SSE via fetch+ReadableStream. Imports BUSINESS_ANALYST_PROMPT from T005. Heartbeat 15s (N4). 90s timeout closes half-open connections. Append user+assistant to overviewtranscripts. On approve, patch section into draft content. Integration tests: stream chunks, heartbeat, timeout, approve-patch.', priority: 'high', status: 'todo' },
	{ title: 'T013: POST /api/overview/draft/:id/paste-analyze — Paste flow with C15 bug-report fallback (A9)', description: 'Accept { content: text|base64image }. 10k soft cap; overflow returns { error: too_large, handoff: import } (FR-013 AC3) — no truncation. SSE stream of per-section proposals via T005 prompt + T008 chunker (vision LLM for images). Writes ONLY AI analysis to transcripts, raw paste dropped (C16). Unresolvable format writes bug report to specs/Project-Scope/025-project-overview-builder/bug-reports/YYYY-MM-DD-paste-format-unsupported-<hash>.md with sanitized sample (C15). Inline bug-report helper (G2 judgment #4).', priority: 'high', status: 'todo' },
	{ title: 'T014: POST /api/overview/draft/:id/import — File/URL import with chunking (A10)', description: 'Accept { source: file, filename, mimetype, payload } | { source: url, url }. File path dispatches to G5 parsers by mimetype. URL path calls T007 (allowlist + SSRF guard). Both run through T008 chunker. Raw content + AI analysis + sourceuri to transcripts (C16 asymmetry). URL imports upsert importcache. 500k hard ceiling rejected with clear message. Integration tests: each file type, each allowlisted host, rejection paths.', priority: 'high', status: 'todo' },
	{ title: 'T015: POST /api/overview/draft/:id/import/refresh — Re-import (A11)', description: 'URL-sourced imports only; file imports return { error: not_refreshable }. Deletes matching importcache row, re-runs T014 URL path, updates fetchedat. Timestamp shown in UI (N10). Integration tests: URL refresh succeeds, file-source returns error.', priority: 'medium', status: 'todo' },
	{ title: 'T016: POST /api/overview/draft/:id/submit-proposal — Handoff to spec-024 (A5, C7)', description: 'Transition draft status to submitted. Call into spec-024 pending-queue handoff — DO NOT BYPASS spec-024 contract (C7). Proposer retains edit access until admin accepts (FR-011 AC3). Integration test verifies spec-024 queue receives handoff payload.', priority: 'high', status: 'todo' },
	{ title: 'T017: POST /api/overview/draft/:id/create-project — Create project + first file write (A6)', description: 'Create projects row, flip draft to accepted + set projectid. Call T006 to write projectoverview.md at repo root (first write). Upsert projectdocuments with doctype=ProjectOverview, specid=null. GET /api/admin/doc-status immediately returns non-null projectOverview timestamp (FR-011 AC2). Integration tests: project row exists, file written, doc-status timestamp present.', priority: 'high', status: 'todo' },

	// G4 — PDF Export
	{ title: 'T018: GET /api/overview/draft/:id/pdf — Reuse Puppeteer pipeline with Mermaid fidelity (A7)', description: 'Reuse projectlifecycle.md Puppeteer pipeline (C4). Markdown → HTML (Mermaid rendered in Puppeteer page context, not CLI subprocess — reuses same browser for PDF render). Stream application/pdf, Content-Disposition attachment. Filename: overview-<projectname>-<date>.pdf; for drafts without project, overview-draft-<shortid>-<date>.pdf. Proposer scoped to own drafts (C13). Mermaid fidelity test fixture (pie + bar + xychart-beta + gantt) folded into integration suite per Q3.', priority: 'medium', status: 'todo' },

	// G5 — File Parsers
	{ title: 'T019: PDF parser using pdf-parse (src/server/parsers/pdf-parser.ts)', description: 'parsePdf(buffer) returns plain text. 500k cap. Encrypted/password PDFs return UnsupportedFormatError → T014 routes to C15. Unit tests: text PDF, scanned-only PDF (fallback), encrypted PDF rejection, 500k cap.', priority: 'medium', status: 'todo' },
	{ title: 'T020: DOCX parser using mammoth (src/server/parsers/docx-parser.ts)', description: 'parseDocx(buffer) returns markdown via mammoth.convertToMarkdown. Preserves headings/lists/bold/italic/tables. Strips images. Image-only detection: if stripped output < 100 chars AND source > 100KB, return UnsupportedFormatError for C15 fallback. Size-cap before unzip (zip-bomb defense). 500k cap.', priority: 'medium', status: 'todo' },
	{ title: 'T021: HTML parser using html-to-text (src/server/parsers/html-parser.ts)', description: 'parseHtml(buffer) returns markdown. Strips script/style/iframe/inline-event-handlers at parse time (not render — defense in depth). Handles UTF-8 + common encodings. Rejects billion-laughs/compression-bomb inputs. 500k cap.', priority: 'medium', status: 'todo' },

	// G6 — Frontend Shell
	{ title: 'T022: Route /overview/:draftId + OverviewEditorPage (FR-001, N1)', description: 'Register /overview/:draftId as SIBLING route to Admin Dashboard — NOT nested (N1, past full-screen attempts leaked chrome). OverviewEditorPage.tsx renders 75/25 split at >=1280px. Back button returns to origin tracked via router state. Orchestrates save state (dirty flag, last-saved, pending-save). Uses useOverviewDraft hook.', priority: 'high', status: 'todo' },
	{ title: 'T023: MarkdownEditorPane — @uiw/react-md-editor with raw Mermaid (FR-002, C5, N2)', description: 'Library: @uiw/react-md-editor (N2 decision). Live preview for headings/lists/tables/code/links. Mermaid fenced blocks stay raw (C5). Keyboard shortcuts: bold/italic/heading/list/link. Emits onChange(markdown). Accessible keyboard nav.', priority: 'high', status: 'todo' },
	{ title: 'T024: EditorToolbar — save status + commit button + PDF export (FR-008, FR-011, FR-012)', description: 'Four elements: autosave status indicator (Saved X ago / Saving / Unsaved — saving in Ns), manual Save button, contextual commit button (Submit Proposal | Create Project) disabled until six required sections have non-placeholder content (FR-011 AC1), Export PDF. beforeunload browser guard + react-router navigate block on unsaved changes.', priority: 'medium', status: 'todo' },

	// G7 — AI Pane + Dialogs
	{ title: 'T025: AIPane — three entry modes + SSE chat + transcript (FR-004/005/006)', description: '1/4-width panel. Top: three entry mode buttons (Interview, Paste to analyze, Import). Chat scrollback from useOverviewDraft transcript. Input: Enter-send / Shift-Enter newline. SSE streaming via useAiMessage. [A]pprove/[C]hange/[E]xplain/[Add] per assistant msg. On approve: route through SectionWriteConfirm if target has existing content. Draft-from-prompt per-section (FR-005) — button in each editor section header. Heartbeat retry banner on >30s silence (N4).', priority: 'medium', status: 'todo' },
	{ title: 'T026: PasteAnalyzeDialog — 10k counter + overflow handoff (FR-013)', description: 'Modal from AIPane paste button. Textarea with live char counter (amber 9000, red 10000). onPaste captures clipboard image as base64 (thumbnail preview shown). Overflow >10k: non-truncating banner "Content too large — switch to import?" with button opening ImportDialog seeded with pasted content as .txt file (FR-013 AC3). Submit calls usePasteAnalyze, closes dialog, AIPane takes over section walkthrough.', priority: 'medium', status: 'todo' },
	{ title: 'T027: ImportDialog — two tabs + client-side allowlist + chunk progress (FR-014)', description: 'Modal with tabs "From File" (drag-drop for .md/.txt/.pdf/.docx/.html + 500k client-side check) and "From URL" (input validated against shared src/shared/url-allowlist.ts constants — prevents client/server drift). Chunk progress indicator ("Analyzing chunk 3 of 8…"). Handoff to AIPane when section mapping starts. Re-import button visible on URL-sourced imports in AIPane sidebar (wires to T015).', priority: 'medium', status: 'todo' },
	{ title: 'T028: SectionWriteConfirm — Replace/Merge/Skip with diff preview (FR-013 AC6, FR-014 AC7)', description: 'Modal fires ONLY on non-empty section collision (empty sections bypass — direct write). Three buttons: Replace (overwrite), Merge (append proposed with \\n\\n separator — deterministic, no second LLM call), Skip (leave untouched, advance). Preview diff above buttons: current vs proposed.', priority: 'medium', status: 'todo' },

	// G8 — Client Hooks
	{ title: 'T029: Core draft hooks A1-A8 (src/client/hooks/overview/)', description: 'useOverviewDraft, useCreateDraft, useSaveOverviewDraft (2s debounce + manual save), useAiMessage (SSE via fetch+ReadableStream — NOT EventSource; POST bodies needed), useSubmitProposal, useCreateProject, useExportPdf. Shared TanStack query key [overview-draft, id]. Optimistic PUT updates with merge-by-timestamp conflict resolution. Unit tests with mocked fetch.', priority: 'medium', status: 'todo' },
	{ title: 'T030: Paste + import hooks A9-A11', description: 'usePasteAnalyze (SSE stream, approve/reject section API). useImportDraft (file upload OR URL; surfaces {currentChunk, totalChunks} for ImportDialog progress). useReimportDraft (throws on file-sourced call; invalidates importcache). All three invalidate [overview-draft, id] after section approvals.', priority: 'medium', status: 'todo' },

	// G9 — Admin Dashboard
	{ title: 'T031: AdminDashboard — New Project + New Proposal launch buttons (FR-009)', description: 'Add TWO side-by-side buttons: "New Project" (ADMIN only) and "New Proposal" (company users + invited proposers). Each calls useCreateDraft with appropriate mode, then navigate(/overview/:draftId). Cancelling leaves draft in status=draft (FR-009 AC2). Role gating client + server (A1). Does NOT replace existing CreateProjectModal — this is a SECOND button for overview-guided project creation.', priority: 'medium', status: 'todo' },
	{ title: 'T032: ProposalList — Edit action + Export PDF menu (FR-010, FR-012 AC1)', description: 'Per-row Edit action gated by editEligibility flag from A8 (author-or-admin AND not accepted). Opens /overview/:draftId preloaded (no new projectdocuments row — FR-010 AC2). Last-edited timestamp updates on save. Export PDF in 3-dot menu (proposer scoped to own drafts, C13). Concurrent-edit UX (N3): PUT reject during admin-accept shows toast "This proposal was just accepted — your changes cannot be saved" (non-blocking).', priority: 'medium', status: 'todo' },

	// G10 — Proposals API Extension
	{ title: 'T033: Extend GET /api/proposals — editEligibility + lastEditedAt (A8)', description: 'Add per-row editEligibility: boolean — true if author pre-accept OR admin OR consultant on same company. Add lastEditedAt: ISO string — max(overviewdrafts.updatedat) for the proposal. Strictly additive — existing consumers ignoring fields continue to work. Integration tests cover full matrix (author/admin/consultant/outsider × pre-accept/post-accept).', priority: 'medium', status: 'todo' },

	// G11 — Testing
	{ title: 'T034: Unit tests — G2 utilities + G1 schema', description: 'URL allowlist (T007): allowlisted pass, non-allowlisted rejected, DNS-rebind to RFC1918/loopback/cloud-metadata rejected, timeout fires. Text chunker (T008): 8k boundary, 500k ceiling rejection, 80-call cap. Atomic persistence (T006): happy path, file-write rollback DB, DB rollback file, concurrent-save optimistic lock. BA prompt parity (T005): single module verified. Schema (G1): insert/update/delete, FK cascade, unique constraints, enum rejection.', priority: 'high', status: 'todo' },
	{ title: 'T035: Integration tests — draft CRUD + AI interview', description: 'A1 both modes + unauth 401. A2 author 200 / other 403 / admin any-company / consultant same-company. A3 happy path, file-write failure rolls back DB, concurrent-save stale error (N3), post-accept rejection (FR-011 AC3). A4 SSE chunks, 15s heartbeat, 90s timeout, approve patches section.', priority: 'high', status: 'todo' },
	{ title: 'T036: Integration tests — paste-analyze (A9) + C15 bug-report fallback', description: 'FR-013 ACs: text happy path, markdown paste, image paste (vision LLM returns content), overflow returns handoff error (AC3), Replace/Merge/Skip on approved writes (AC6), missing-section re-paste prompt (AC7), unresolvable format writes bug report file to specs/Project-Scope/025-project-overview-builder/bug-reports/ with sanitized sample. C16: raw paste NOT in transcripts (post-request DB query assertion).', priority: 'high', status: 'todo' },
	{ title: 'T037: Integration tests — import (A10/A11) + security', description: 'FR-014 ACs: each file type upload + parse round-trip (fixtures in tests/fixtures/parsers/). Each allowlisted URL host — mock upstream. Security: non-allowlisted host rejected, DNS-rebind rejected, 500k ceiling, 10s timeout. Chunking: 50k import produces >6 chunks, accumulating context passes prior mappings. Cache: first import populates importcache, second returns cached, A11 invalidates + refetches, file-source A11 returns not_refreshable error. C16: raw + AI analysis + sourceuri all in transcripts.', priority: 'high', status: 'todo' },
	{ title: 'T038: Integration tests — submit + create-project + spec-024 handoff', description: 'Submit enqueues to spec-024 pending queue (verify handoff payload, do NOT bypass). Create Project: projects row created, draft flipped to accepted, projectoverview.md at repo root (fs check), projectdocuments upserted, GET /api/admin/doc-status returns non-null timestamp (AC2). N3 race: author PUT during admin accept rejected. Post-accept proposer edit rejected (AC3).', priority: 'high', status: 'todo' },
	{ title: 'T039: Integration tests — proposals extension (A8) matrix', description: 'editEligibility: author-owned pre-accept true / post-accept false; admin on company always true; consultant on company always true; outside company row hidden. lastEditedAt updates on draft PUT. Backwards compatibility: ignoring-consumers still work.', priority: 'medium', status: 'todo' },
	{ title: 'T040: E2E Playwright tests — US1-US4 + paste + import happy paths', description: 'US1 new proposal: create → interview 6 sections → submit → appears in spec-024 queue. US2 new project: admin creates via editor → appears on dashboard → ReportLinkCard non-null timestamp. US3 re-edit: proposer Edit → existing content + transcript load → revise Goals → save → timestamp updates. US4 PDF export: from toolbar + from row menu → downloaded PDF contains 6 sections + Mermaid rendered (text-extraction assertion, Q3). Plus: one paste E2E (textarea → section mapping → approve → editor fills), one URL import E2E (public GitHub URL → chunked analysis → section mapping → approve).', priority: 'medium', status: 'todo' },

	// G12 — Docs & Cleanup
	{ title: 'T041: Update CLAUDE.md conventions + Claude Projects N7 help text', description: 'Add "Project Overview Builder conventions" section to CLAUDE.md: (a) projectoverview.md repo-root location, (b) dual-persistence pattern extending projectlifecycle.md precedent, (c) shared host allowlist at src/shared/url-allowlist.ts, (d) BA prompt single-source at src/server/ai/prompts/business-analyst.ts. Add in-app tooltip/help for N7: "Have a Claude Project? Export claude.md to a GitHub repo, then paste the URL into Import."', priority: 'low', status: 'todo' },
	{ title: 'T042: Late-bound AC verification + lifecycle sync + status flip', description: 'Manually verify N10: Re-import button visible on URL-sourced imports only, last-fetched timestamp renders + updates after A11. Smoke-verify Success Criterion #2: 10 sequential Create Project flows each produce non-null projectOverview timestamp in GET /api/admin/doc-status — no silent "not created" states. Confirm specs/025-project-overview-builder/{spec.md,plan.md,tasks.md,tests.md,lifecycle.json,quickstart.md,checklists/requirements.md} exist and reference Project-Scope/025 as upstream. Update specs/projectlifecycle.md with spec 025 in Implementation phase (Mermaid charts recalculated per CLAUDE.md). Push projectlifecycle.md to DB via ProjectDocumentService.upsertDocument. Flip 025 spec status draft → planned.', priority: 'low', status: 'todo' },
];

async function main(): Promise<void> {
	if (!fs.existsSync(SCOPE_PATH)) {
		throw new Error(`Scope file not found: ${SCOPE_PATH}`);
	}
	const scopeContent = fs.readFileSync(SCOPE_PATH, 'utf-8');

	console.log(`\n[createspecs wrapper] Calling handleCreateSpecs with ${tasks.length} tasks`);
	console.log(`[createspecs wrapper] Scope content: ${scopeContent.length} chars`);

	const { result, audit } = await handleCreateSpecs({
		specNumber: '025',
		featureName: 'Project Overview Builder',
		scopeContent,
		phase: 'design',
		priority: 'high',
		tasks,
		generateLifecycle: true,
		generateTests: true,
		user: 'andy@wxperts.com',
	});

	// Persist audit record alongside the generated artifacts
	const auditPath = path.resolve(process.cwd(), `specs/025-project-overview-builder/audit-createspecs.json`);
	fs.writeFileSync(auditPath, JSON.stringify(audit, null, 2));
	console.log(`\n[createspecs wrapper] Audit record: ${auditPath}`);

	console.log(`\n[createspecs wrapper] Result summary:`);
	console.log(JSON.stringify(result, null, 2));
}

main().catch((err: Error) => {
	console.error(`Fatal: ${err.message}`);
	console.error(err.stack);
	process.exit(1);
});
