import { readFileSync } from 'fs';
import { handleImplementCommand } from '../core/orchestrator/command-handlers/implement';

// SCOPE-081 — apply a new fenced file via the implement orchestrator so the
// BEGIN/END fences are written by the kit (never hand-authored). The module body
// is generated by the editor AI and passed as a `create` proposal.
//   npx tsx run-implement-081.ts <task> <repoRelTargetPath> <bodyFilePath> [--dry-run]
const task = process.argv[2];
const target = process.argv[3];
const bodyPath = process.argv[4];
const DRY = process.argv.includes('--dry-run');

async function main(): Promise<void> {
  const body = readFileSync(bodyPath, 'utf-8');
  const res = await handleImplementCommand({
    scope: '081',
    task,
    dryRun: DRY,
    projectRoot: process.cwd(),
    proposal: [{ path: target, body, action: 'create' }],
  });
  console.log(`\n[implement 081/${task}] exit=${res.exitCode} — ${res.message}`);
  console.log(`  written: ${res.filesWritten.join(', ') || '(none)'}`);
  console.log(`  skipped: ${res.filesSkipped.join(', ') || '(none)'}`);
  if (res.warnings?.length) console.log(`  warnings:\n    - ${res.warnings.join('\n    - ')}`);
}

main().catch((err: Error) => {
  console.error(`Fatal: ${err.message}`);
  process.exitCode = 1;
});
