#!/usr/bin/env python3
"""
clarion-views-to-scope.py - Document every Clarion VIEW / browse data source as ONE queries scope.

Input : pre-convert/*.view.md  (each embeds a verbatim VIEW ... END in a ```clarion fence). Also
        scans *.page.md / *.proc.md fences for literal PROP:SQL / SQL() strings.
Output: rebuild/scopes/VIEW-queries-scope.md

Per VIEW: the primary FILE (from VIEW(file)), the PROJECT-ed columns, JOIN-ed files, ORDER/FILTER,
and a RECONSTRUCTED SQL SELECT. Clarion expresses joins through the dictionary's relations, so the
emitted SELECT is reconstructed from the JOIN()/PROJECT() structure — verify joins against intent.

Usage:
    python scripts/clarion-views-to-scope.py --src pre-convert --out rebuild/scopes
"""
import argparse
import glob
import os
import re

import os as _wmos, sys as _wmsys
_wmsys.path.insert(0, _wmos.path.dirname(_wmos.path.abspath(__file__)))
from wxkanban_watermark import stamp_markdown

FENCE_RE = re.compile(r"```clarion\n(.*?)```", re.S)


def fences(path):
    return FENCE_RE.findall(open(path, encoding="utf-8").read())


def paren(line, name):
    m = re.search(rf"\b{name}\s*\(([^)]*)\)", line, re.I)
    return m.group(1).strip() if m else None


def parse_view(text):
    primary = None
    projects, joins, order, filt = [], [], None, None
    for ln in text.split("\n"):
        s = ln.strip()
        up = s.upper()
        if up.startswith("VIEW") or "VIEW(" in up:
            primary = primary or paren(s, "VIEW")
        if up.startswith("PROJECT"):
            cols = paren(s, "PROJECT")
            if cols:
                projects += [c.strip() for c in cols.split(",") if c.strip()]
        if up.startswith("JOIN"):
            j = paren(s, "JOIN")
            if j:
                joins.append([p.strip() for p in j.split(",")])
        if "ORDER(" in up:
            order = paren(s, "ORDER")
        if "FILTER(" in up:
            filt = paren(s, "FILTER")
    return dict(primary=primary, projects=projects, joins=joins, order=order, filter=filt)


def reconstruct_sql(v):
    cols = ", ".join(v["projects"]) if v["projects"] else "*"
    sql = [f"SELECT {cols}", f"FROM {v['primary'] or '<primary file>'}"]
    for j in v["joins"]:
        tbl = j[-1] if j else "<file>"
        rel = j[0] if len(j) > 1 else ""
        sql.append(f"  JOIN {tbl} ON /* dictionary relation {rel} — confirm join columns */")
    if v["filter"]:
        sql.append(f"WHERE /* Clarion FILTER: {v['filter']} */")
    if v["order"]:
        sql.append(f"ORDER BY {v['order']}")
    return "\n".join(sql) + ";"


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--src", default="pre-convert")
    ap.add_argument("--out", default="rebuild/scopes")
    args = ap.parse_args()

    out = ["# Queries scope (Clarion VIEW / browse data sources)", "",
           "_Generated by cwConversion. Each VIEW below is reconstructed from its PROJECT()/JOIN() "
           "structure; Clarion expresses joins through dictionary relations, so **verify the join "
           "columns** against the dictionary before trusting the SQL._", ""]
    n = 0
    for path in sorted(glob.glob(os.path.join(args.src, "*.view.md"))):
        name = os.path.basename(path).split(".")[0]
        for body in fences(path):
            v = parse_view(body)
            n += 1
            out.append(f"## {name}")
            out.append("")
            out.append(f"- **Primary file:** `{v['primary'] or '?'}`")
            out.append(f"- **Projected columns:** {', '.join(f'`{c}`' for c in v['projects']) or '(all)'}")
            if v["joins"]:
                out.append(f"- **Joins:** " + "; ".join(
                    f"`{j[-1]}`" + (f" via `{j[0]}`" if len(j) > 1 else "") for j in v["joins"]))
            if v["order"]:
                out.append(f"- **Order:** `{v['order']}`")
            if v["filter"]:
                out.append(f"- **Filter:** `{v['filter']}`")
            out.append("")
            out.append("Reconstructed SQL:\n")
            out.append("```sql")
            out.append(reconstruct_sql(v))
            out.append("```")
            out.append("")

    # literal SQL embedded in procedures/windows
    lits = []
    for path in glob.glob(os.path.join(args.src, "*.proc.md")) + glob.glob(os.path.join(args.src, "*.page.md")):
        for body in fences(path):
            for m in re.finditer(r"PROP:SQL\s*=\s*'([^']+)'|\bSQL\(\s*'([^']+)'", body, re.I):
                lits.append((os.path.basename(path), m.group(1) or m.group(2)))
    if lits:
        out.append("## Literal PROP:SQL / SQL() strings found")
        out.append("")
        for src, sql in lits[:50]:
            out.append(f"- `{src}`: `{sql.strip()}`")
        out.append("")

    if n == 0 and not lits:
        out.append("_No VIEW structures or literal SQL found in the source._")

    os.makedirs(args.out, exist_ok=True)
    dest = os.path.join(args.out, "VIEW-queries-scope.md")
    open(dest, "w", encoding="utf-8").write(
        stamp_markdown("\n".join(out) + "\n", kind='converted', generator='cwConversion'))
    print(f"views={n}  literal-sql={len(lits)}")
    print(f"  -> {dest}")


if __name__ == "__main__":
    main()
