#!/usr/bin/env python3
"""
clarion-procs-to-scope.py - Document Clarion procedures/routines/embeds as ONE business-logic scope.

Input : pre-convert/*.proc.md  (each embeds verbatim Clarion in a ```clarion fence).
Output: rebuild/scopes/PROC-procedures-scope.md

Per procedure: the PROCEDURE(...) prototype/parameters, ROUTINEs, data files touched (ABC
Access:/Relate: and *:Update/Insert/Delete/Fetch ops), and a flag for record-validation /
referential-integrity logic — the Clarion analogue of a database trigger, which has NO UI and must be
ported to the API/server layer, NOT scaffolded as a page.

Usage:
    python scripts/clarion-procs-to-scope.py --src pre-convert --out rebuild/scopes
"""
import argparse
import glob
import os
import re

import os as _wmos, sys as _wmsys
_wmsys.path.insert(0, _wmos.path.dirname(_wmos.path.abspath(__file__)))
import sys  # noqa: E402
import wxconv_redact as rd  # noqa: E402 - the watermark stamp now lives inside rd.write_text()

FENCE_RE = re.compile(r"```clarion\n(.*?)```", re.S)
PROTO_RE = re.compile(r"^\s*([A-Za-z_]\w*)\s+PROCEDURE\s*\(([^)]*)\)", re.I)
ROUTINE_RE = re.compile(r"^\s*([A-Za-z_]\w*)\s+ROUTINE\b", re.I)
ACCESS_RE = re.compile(r"\b(?:Access|Relate|Hide:Access):([A-Za-z_]\w*)", re.I)
DATAOP_RE = re.compile(r"\b([A-Za-z_]\w*):(Update|Insert|Delete|Fetch|TryFetch|TryUpdate|TryInsert|Next|Previous|Open|Close)\b", re.I)
VALIDATION_HINTS = ("referential", "RI ", "Update.", "Delete.", "Insert.", "constraint",
                    "duplicate", "must be", "cannot delete", "OnViolation", "DescribeTrigger")


def fences(path):
    return FENCE_RE.findall(open(path, encoding="utf-8").read())


def summarize(text):
    proto = None
    routines, files, dataops = [], set(), set()
    validation = False
    for ln in text.split("\n"):
        if proto is None:
            m = PROTO_RE.match(ln)
            if m:
                proto = (m.group(1), m.group(2).strip())
        rm = ROUTINE_RE.match(ln)
        if rm:
            routines.append(rm.group(1))
        for m in ACCESS_RE.finditer(ln):
            files.add(m.group(1))
        for m in DATAOP_RE.finditer(ln):
            files.add(m.group(1))
            dataops.add(f"{m.group(1)}:{m.group(2)}")
        low = ln.lower()
        if any(h.lower() in low for h in VALIDATION_HINTS):
            validation = True
    return dict(proto=proto, routines=routines, files=sorted(files),
                dataops=sorted(dataops), validation=validation)


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--src", default="pre-convert")
    ap.add_argument("--out", default="rebuild/scopes")
    rd.add_redaction_args(ap, scan=False)
    args = ap.parse_args()

    state = rd.RedactionState()

    procs = []
    for path in sorted(glob.glob(os.path.join(args.src, "*.proc.md"))):
        name = os.path.basename(path).split(".")[0]
        text = "\n".join(fences(path))
        procs.append((name, summarize(text)))

    val = [n for n, s in procs if s["validation"]]
    out = ["# Server / business-logic scope (Clarion procedures & embeds)", "",
           "_Generated by cwConversion. This is the application's backend logic — port it to the "
           "API/server layer the React pages call. Do NOT scaffold these as pages._", ""]
    if val:
        out += ["> **Validation / referential-integrity callout.** These procedures contain "
                "record-validation or RI logic (the Clarion equivalent of triggers) and must move to "
                "the server/API layer, enforced before writes:",
                ""]
        out += [f"> - `{n}`" for n in val]
        out += [""]

    out.append("## Procedures")
    out.append("")
    for name, s in procs:
        proto = f"`{s['proto'][0]}({s['proto'][1]})`" if s["proto"] else "_(no prototype found)_"
        out.append(f"### {name}")
        out.append("")
        out.append(f"- **Prototype:** {proto}")
        if s["routines"]:
            out.append(f"- **Routines:** {', '.join(f'`{r}`' for r in s['routines'])}")
        if s["files"]:
            out.append(f"- **Files touched:** {', '.join(f'`{f}`' for f in s['files'])}")
        if s["dataops"]:
            out.append(f"- **Data operations:** {', '.join(f'`{d}`' for d in s['dataops'])}")
        if s["validation"]:
            out.append("- ⚠️ **Contains validation / RI logic — port to server-side enforcement.**")
        out.append("")

    if not procs:
        out.append("_No procedure/logic files found in the source._")

    os.makedirs(args.out, exist_ok=True)
    dest = os.path.join(args.out, "PROC-procedures-scope.md")
    # [SCOPE 125 / T011] Through the shared funnel (FR-007): redacts, accumulates findings and
    # stamps the watermark on .md, so the manual stamp_markdown call is gone, not duplicated.
    rd.write_text(dest, "\n".join(out) + "\n", state, generator='cwConversion')
    print(f"procedures={len(procs)}  with-validation={len(val)}")
    print(f"  -> {dest}")

    # [SCOPE 125 / T011] Credential report, rendered from the accumulated state and written
    # last so it covers every emission this run made. The summary prints unconditionally,
    # including when nothing was found: a run that says nothing about credentials is the
    # defect this scope fixes.
    sidecar_path = os.path.join(args.out, rd.SIDECAR_NAME)
    if state.findings:
        rd.write_text(sidecar_path, rd.render_sidecar(state), state, generator='cwConversion')
    print(rd.summary_line(state, sidecar_path))
    return rd.exit_code(len(state.findings), args.fail_on_secrets)


if __name__ == "__main__":
    sys.exit(main())
