import { resolve, dirname, extname } from "path";
import {
  readFileSync,
  writeFileSync,
  existsSync,
  mkdirSync,
  renameSync,
  unlinkSync,
} from "fs";
// Spec 019 R6a — code-emitting handlers MUST NOT import the AI client.
// The user's editor AI generates the proposal; the kit validates + applies.
import {
  loadSpecBundle,
  findTask,
  verifyTaskUnblocked,
  SpecNotFoundError,
  TaskNotFoundError,
  TaskBlockedByDependenciesError,
} from "../spec-loader";
import {
  buildImplementPrompt,
  parseProposal,
  ProposalParseError,
  ProposedFile,
} from "../implement-prompt";
import {
  emitFence,
  NoDetectableUnitError,
  TaskFenceRow,
} from "../fence-emitter";
import { isSuppressed } from "../language-matrix";
import { isDriftDetected } from "../content-hash";
import { markTaskDone } from "../tasks-md-writer";
import {
  FenceDbClient,
  applyFenceDbWrites,
  loadExistingFencesForFile,
} from "../fence-db";

export interface ImplementOptions {
  scope: string;
  task: string;
  dryRun?: boolean;
  replace?: boolean;
  modify?: boolean;
  acceptDrift?: boolean;
  specsRoot?: string;
  projectRoot?: string;
  projectId?: string;
  fileOverride?: string;
  // Spec 019 R6a — proposal generated by the user's editor AI.
  // CLI passes `--input <path>` (or `--input -` for stdin); MCP path passes
  // the structured proposal directly. Exactly one MUST be supplied; if both
  // are absent the handler emits the prompt to stdout for the user's AI.
  inputPath?: string;
  proposal?: ProposedFile[];
  // Raw JSON string (e.g. from MCP tool argument) — parsed via parseProposal.
  proposalJson?: string;
  // When true, write the prompt to stdout instead of applying anything.
  // Used by callers that want to feed the prompt to an editor AI manually.
  printPromptOnly?: boolean;
  dbClient?: FenceDbClient;
}

export interface ImplementResult {
  exitCode: 0 | 1 | 2 | 3;
  message: string;
  filesWritten: string[];
  filesSkipped: string[];
  filesDeleted: string[];
  warnings: string[];
  // When `printPromptOnly` is true, the prompt is returned here instead of
  // applied. Lets the CLI emit it without coupling to console.
  prompt?: { systemPrompt: string; userPrompt: string };
}

export class ImplementError extends Error {
  constructor(public readonly exitCode: 1 | 2 | 3, message: string) {
    super(message);
    this.name = "ImplementError";
  }
}

export async function handleImplementCommand(
  options: ImplementOptions,
): Promise<ImplementResult> {
  const projectRoot = options.projectRoot ?? process.cwd();
  const specsRoot = resolve(projectRoot, options.specsRoot ?? "specs");

  let bundle;
  try {
    bundle = loadSpecBundle(specsRoot, options.scope);
  } catch (err) {
    if (err instanceof SpecNotFoundError) {
      throw new ImplementError(2, err.message);
    }
    throw err;
  }

  let task;
  try {
    task = findTask(bundle, options.task);
  } catch (err) {
    if (err instanceof TaskNotFoundError) {
      throw new ImplementError(2, err.message);
    }
    throw err;
  }

  try {
    verifyTaskUnblocked(bundle, task);
  } catch (err) {
    if (err instanceof TaskBlockedByDependenciesError) {
      throw new ImplementError(1, err.message);
    }
    throw err;
  }

  // Spec 019 R6a — resolve the proposal from one of four sources, in order:
  //   1. options.proposal     — already-parsed (MCP path, tests)
  //   2. options.proposalJson — raw JSON string (MCP path, tests, stdin)
  //   3. options.inputPath    — read JSON from file ('-' = stdin)
  //   4. (none) + printPromptOnly — emit the prompt for the user's editor AI
  // The kit no longer generates the proposal itself; the editor AI does.
  const { systemPrompt, userPrompt } = buildImplementPrompt({ bundle, task });

  if (options.printPromptOnly) {
    return {
      exitCode: 0,
      message: `implement ${options.scope}/${options.task} — prompt only (no input provided)`,
      filesWritten: [],
      filesSkipped: [],
      filesDeleted: [],
      warnings: [],
      prompt: { systemPrompt, userPrompt },
    };
  }

  let proposal: ProposedFile[];
  if (options.proposal) {
    proposal = options.proposal;
  } else {
    let raw: string;
    if (typeof options.proposalJson === "string") {
      raw = options.proposalJson;
    } else if (options.inputPath) {
      try {
        raw =
          options.inputPath === "-"
            ? readFileSync(0, "utf-8") // fd 0 = stdin
            : readFileSync(resolve(projectRoot, options.inputPath), "utf-8");
      } catch (err) {
        throw new ImplementError(
          2,
          `Cannot read --input ${options.inputPath}: ${(err as Error).message}`,
        );
      }
    } else {
      throw new ImplementError(
        2,
        `implement ${options.scope}/${options.task} requires --input <path> (or --input - for stdin), or pass --print-prompt to emit the prompt for your editor AI. The kit no longer generates code itself (Spec 019 R6a).`,
      );
    }
    try {
      proposal = parseProposal(raw);
    } catch (err) {
      if (err instanceof ProposalParseError) {
        throw new ImplementError(3, err.message);
      }
      throw err;
    }
  }

  if (options.fileOverride) {
    proposal = proposal.filter((p) => p.path === options.fileOverride);
    if (proposal.length === 0) {
      throw new ImplementError(
        2,
        `--file ${options.fileOverride} not present in AI proposal for ${task.id}`,
      );
    }
  }

  const filesWritten: string[] = [];
  const filesSkipped: string[] = [];
  const filesDeleted: string[] = [];
  const warnings: string[] = [];

  const useDb = !options.dryRun && options.dbClient && options.projectId;
  if (useDb) {
    await options.dbClient!.begin();
  }

  try {
    for (const file of proposal) {
      const absPath = resolve(projectRoot, file.path);
      const currentContent = existsSync(absPath)
        ? readFileSync(absPath, "utf-8")
        : null;

      const existingFences: TaskFenceRow[] = options.dbClient
        ? (await loadExistingFencesForFile(
            options.dbClient,
            options.projectId ?? "",
            file.path,
          )).map((r) => ({
            id: r.id,
            filepath: r.filepath,
            unitkind: r.unitkind as TaskFenceRow["unitkind"],
            unitname: r.unitname,
            ownerscope: r.ownerscope,
            ownertask: r.ownertask,
            description: r.description,
            contenthash: r.contenthash,
            linestart: r.linestart,
            lineend: r.lineend,
          }))
        : [];

      if (
        !options.acceptDrift &&
        currentContent &&
        existingFences.length > 0
      ) {
        for (const fence of existingFences) {
          const body = currentContent
            .split(/\r?\n/)
            .slice(fence.linestart, fence.lineend)
            .join("\n");
          if (isDriftDetected(body, fence.contenthash)) {
            throw new ImplementError(
              1,
              `${file.path}: fence [SCOPE ${fence.ownerscope} / ${fence.ownertask}] modified out of band. Use --accept-drift to overwrite (logged), or revert manual changes and retry.`,
            );
          }
        }
      }

      // Spec 031 FR-002: delete action branch. Runs after the shared drift check above.
      if (file.action === "delete") {
        if (currentContent === null) {
          throw new ImplementError(
            2,
            `cannot delete ${file.path}: file does not exist`,
          );
        }

        if (options.dryRun) {
          filesSkipped.push(file.path);
          continue;
        }

        unlinkSync(absPath);
        filesDeleted.push(file.path);

        if (useDb) {
          for (const fence of existingFences) {
            await options.dbClient!.query(
              `INSERT INTO taskfencehistory
                 (projectid, filepath, unitkind, unitname,
                  priorownerscope, priorownertask, replacedbyscope, replacedbytask)
               VALUES ($1, $2, $3, $4, $5, $6, $7, $8)`,
              [
                options.projectId,
                file.path,
                fence.unitkind,
                fence.unitname,
                fence.ownerscope,
                fence.ownertask,
                options.scope,
                options.task,
              ],
            );
            await options.dbClient!.query(
              `DELETE FROM taskfencemodifications WHERE taskfenceid = $1`,
              [fence.id],
            );
            await options.dbClient!.query(
              `DELETE FROM taskfences WHERE id = $1`,
              [fence.id],
            );
          }
        }

        continue;
      }

      const mode = options.replace
        ? ("replace" as const)
        : options.modify
        ? ("modify" as const)
        : ("auto" as const);

      const ext = extname(file.path);
      let outputContent = file.body;
      let fenceWarnings: string[] = [];
      let dbWrites = undefined as ReturnType<typeof emitFence>["dbWrites"] | undefined;

      if (!isSuppressed(ext)) {
        try {
          const fenceResult = emitFence({
            filepath: file.path,
            currentContent,
            proposedContent: file.body,
            ownerScope: options.scope,
            ownerTask: options.task,
            description: task.title,
            existingFences,
            mode,
          });
          outputContent = fenceResult.content;
          fenceWarnings = fenceResult.warnings;
          dbWrites = fenceResult.dbWrites;
        } catch (err) {
          if (err instanceof NoDetectableUnitError) {
            warnings.push(`${file.path}: ${err.message}`);
            filesSkipped.push(file.path);
            continue;
          }
          throw err;
        }
      }
      warnings.push(...fenceWarnings);

      if (options.dryRun) {
        filesSkipped.push(file.path);
        continue;
      }

      mkdirSync(dirname(absPath), { recursive: true });
      const tmpPath = `${absPath}.tmp.${process.pid}`;
      writeFileSync(tmpPath, outputContent);
      renameSync(tmpPath, absPath);
      filesWritten.push(file.path);

      if (useDb && dbWrites) {
        await applyFenceDbWrites(
          options.dbClient!,
          options.projectId ?? "",
          file.path,
          dbWrites,
        );
      }
    }

    if (useDb) {
      await options.dbClient!.commit();
    }

    if (!options.dryRun) {
      markTaskDone(bundle.tasksMdPath, task.id);
    }

    return {
      exitCode: 0,
      message:
        filesDeleted.length > 0
          ? `implement ${options.scope}/${options.task} — wrote ${filesWritten.length} file(s), deleted ${filesDeleted.length}, skipped ${filesSkipped.length}, ${warnings.length} warning(s)`
          : `implement ${options.scope}/${options.task} — wrote ${filesWritten.length} file(s), skipped ${filesSkipped.length}, ${warnings.length} warning(s)`,
      filesWritten,
      filesSkipped,
      filesDeleted,
      warnings,
    };
  } catch (err) {
    if (useDb) {
      try {
        await options.dbClient!.rollback();
      } catch {
        // best effort
      }
    }
    if (err instanceof ImplementError) throw err;
    throw new ImplementError(
      3,
      `Filesystem or DB error: ${(err as Error).message}`,
    );
  }
}

// ─────────────────────────────────────────────────────────────────────────────
// Spec 031 Phase 2 — Batch mode: implement <scope> walks tasks.md in order.
// ─────────────────────────────────────────────────────────────────────────────

export interface BatchImplementOptions {
  scope: string;
  projectRoot?: string;
  specsRoot?: string;
  projectId?: string;
  dryRun?: boolean;
  acceptDrift?: boolean;
  continueOnError?: boolean;
  dbClient?: FenceDbClient;
  // Per-task proposal source. Called once per ready task. Receives the task ID
  // and the built prompt; returns the raw JSON proposal string, or `undefined`
  // to record the task as skipped (no proposal available).
  // Per Spec 019 R6a the kit does not generate proposals itself — this function
  // is the seam where the editor AI's proposal enters the loop.
  proposalSource: (
    taskId: string,
    prompt: { systemPrompt: string; userPrompt: string },
  ) => Promise<string | undefined>;
}

export interface BatchTaskOutcome {
  taskId: string;
  result: ImplementResult | { status: "failed" | "skipped"; reason: string };
}

export interface BatchImplementResult {
  exitCode: 0 | 1 | 2 | 3;
  tasks: BatchTaskOutcome[];
  summary: {
    succeeded: number;
    failed: number;
    skipped: number;
    totalFilesWritten: number;
    totalFilesDeleted: number;
    totalWarnings: number;
  };
}

export async function handleImplementBatchCommand(
  options: BatchImplementOptions,
): Promise<BatchImplementResult> {
  const projectRoot = options.projectRoot ?? process.cwd();
  const specsRoot = resolve(projectRoot, options.specsRoot ?? "specs");

  let bundle;
  try {
    bundle = loadSpecBundle(specsRoot, options.scope);
  } catch (err) {
    if (err instanceof SpecNotFoundError) {
      throw new ImplementError(2, err.message);
    }
    throw err;
  }

  // Sanity: no duplicate task IDs. (Full topological cycle detection requires
  // declared dependencies, which spec-loader does not currently extract — this
  // is the degenerate form per FR-006 implementer note.)
  const seenIds = new Set<string>();
  for (const task of bundle.tasks) {
    if (seenIds.has(task.id)) {
      throw new ImplementError(
        2,
        `tasks.md contains duplicate task id: ${task.id}`,
      );
    }
    seenIds.add(task.id);
  }

  // Walk todo tasks in tasks.md file order. (Future enhancement: parse declared
  // dependencies + topological sort once spec-loader extracts them.)
  const todoTasks = bundle.tasks.filter(
    (t) => t.status.toLowerCase() === "todo",
  );

  const outcomes: BatchTaskOutcome[] = [];
  let highestExitCode: 0 | 1 | 2 | 3 = 0;

  for (const task of todoTasks) {
    const { systemPrompt, userPrompt } = buildImplementPrompt({ bundle, task });
    const prompt = { systemPrompt, userPrompt };

    let proposalJson: string | undefined;
    try {
      proposalJson = await options.proposalSource(task.id, prompt);
    } catch (err) {
      outcomes.push({
        taskId: task.id,
        result: {
          status: "failed",
          reason: `proposal source error: ${(err as Error).message}`,
        },
      });
      if (3 > highestExitCode) highestExitCode = 3;
      if (!options.continueOnError) break;
      continue;
    }

    if (proposalJson === undefined) {
      outcomes.push({
        taskId: task.id,
        result: { status: "skipped", reason: "no proposal provided" },
      });
      continue;
    }

    try {
      const result = await handleImplementCommand({
        scope: options.scope,
        task: task.id,
        projectRoot: options.projectRoot,
        specsRoot: options.specsRoot,
        projectId: options.projectId,
        dryRun: options.dryRun,
        acceptDrift: options.acceptDrift,
        dbClient: options.dbClient,
        proposalJson,
      });
      outcomes.push({ taskId: task.id, result });
    } catch (err) {
      const reason = err instanceof Error ? err.message : String(err);
      const taskExitCode: 1 | 2 | 3 =
        err instanceof ImplementError ? err.exitCode : 3;
      if (taskExitCode > highestExitCode) highestExitCode = taskExitCode;
      outcomes.push({
        taskId: task.id,
        result: { status: "failed", reason },
      });
      if (!options.continueOnError) break;
    }
  }

  const summary = {
    succeeded: 0,
    failed: 0,
    skipped: 0,
    totalFilesWritten: 0,
    totalFilesDeleted: 0,
    totalWarnings: 0,
  };
  for (const outcome of outcomes) {
    if ("status" in outcome.result) {
      if (outcome.result.status === "failed") summary.failed += 1;
      else summary.skipped += 1;
    } else {
      summary.succeeded += 1;
      summary.totalFilesWritten += outcome.result.filesWritten.length;
      summary.totalFilesDeleted += outcome.result.filesDeleted.length;
      summary.totalWarnings += outcome.result.warnings.length;
    }
  }

  return {
    exitCode: highestExitCode,
    tasks: outcomes,
    summary,
  };
}

// ─────────────────────────────────────────────────────────────────────────────
// Spec 031 Phase 2 — Dry-run summary table formatter (used by CLI gateway).
// ─────────────────────────────────────────────────────────────────────────────

export function formatBatchSummaryTable(
  result: BatchImplementResult,
  options?: { verbose?: boolean },
): string {
  const lines: string[] = [];
  const headerCols = ["Task", "Status", "Files written", "Files deleted", "Warnings"];
  lines.push(headerCols.join(" | "));
  lines.push(headerCols.map((c) => "-".repeat(c.length)).join("-|-"));

  for (const outcome of result.tasks) {
    let status: string;
    let written = "0";
    let deleted = "0";
    let warnings = "0";
    if ("status" in outcome.result) {
      status = outcome.result.status;
      // For failed/skipped, surface the reason inline
      const reason = outcome.result.reason;
      lines.push(
        [
          outcome.taskId,
          `${status}: ${reason}`,
          written,
          deleted,
          warnings,
        ].join(" | "),
      );
      continue;
    }
    status = "succeeded";
    written = String(outcome.result.filesWritten.length);
    deleted = String(outcome.result.filesDeleted.length);
    warnings = String(outcome.result.warnings.length);
    lines.push(
      [outcome.taskId, status, written, deleted, warnings].join(" | "),
    );
  }

  lines.push("");
  lines.push(
    `Totals: ${result.summary.succeeded} succeeded, ${result.summary.failed} failed, ${result.summary.skipped} skipped`,
  );
  lines.push(
    `        ${result.summary.totalFilesWritten} file write(s), ${result.summary.totalFilesDeleted} delete(s), ${result.summary.totalWarnings} warning(s)`,
  );

  if (options?.verbose) {
    lines.push("");
    lines.push("--- Per-task detail ---");
    for (const outcome of result.tasks) {
      lines.push("");
      lines.push(`### ${outcome.taskId}`);
      if ("status" in outcome.result) {
        lines.push(`  ${outcome.result.status}: ${outcome.result.reason}`);
      } else {
        lines.push(`  ${outcome.result.message}`);
        if (outcome.result.filesWritten.length > 0) {
          lines.push(`  Written: ${outcome.result.filesWritten.join(", ")}`);
        }
        if (outcome.result.filesDeleted.length > 0) {
          lines.push(`  Deleted: ${outcome.result.filesDeleted.join(", ")}`);
        }
        if (outcome.result.warnings.length > 0) {
          for (const w of outcome.result.warnings) {
            lines.push(`  Warning: ${w}`);
          }
        }
      }
    }
  }

  return lines.join("\n");
}
